#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { GENERATED_THEME_DEFINITIONS } from '../src/components/themes/generated-theme-definitions.mjs';
import { serializePage } from '../src/metadata-serialize.mjs';

const root=path.resolve(import.meta.dirname,'..');
const themesDir=path.join(root,'src/components/themes');
for (const theme of GENERATED_THEME_DEFINITIONS) {
  const runtime=await import(`${pathToFileURL(path.join(themesDir,theme.key,'runtime.jsx')).href}?t=${Date.now()}`);
  const pages=runtime.runtimePages.map(serializePage);
  const metadata={key:theme.key,displayName:theme.displayName,label:theme.label,name:theme.name,scenario:theme.scenario,audience:theme.audience,mode:theme.mode,recipe:theme.recipe};
  fs.writeFileSync(path.join(themesDir,theme.key,'metadata.js'),`// @generated by update-generated-theme-metadata.jsx — DO NOT EDIT.\n\nexport const theme = ${JSON.stringify(metadata,null,2)};\nexport const pages = ${JSON.stringify(pages,null,2)};\n`);
}

const themeDirs=fs.readdirSync(themesDir,{withFileTypes:true}).filter(x=>x.isDirectory()&&/^theme\d+$/.test(x.name)).map(x=>x.name).sort();
const themes=[]; const pages=[];
for (const key of themeDirs) {
  const file=path.join(themesDir,key,'metadata.js');
  if (!fs.existsSync(file)) continue;
  const mod=await import(`${pathToFileURL(file).href}?t=${Date.now()}`);
  themes.push({...mod.theme,pageCount:mod.pages.length}); pages.push(...mod.pages);
}
fs.writeFileSync(path.join(themesDir,'generated-metadata.js'),`export const GENERATED_THEME_PACKS = ${JSON.stringify(themes,null,2)};\n\nexport const GENERATED_THEME_PAGES = ${JSON.stringify(pages,null,2)};\n`);
console.log(`Updated ${themes.length} themes and ${pages.length} pages.`);
