export const LARK_PLUGIN_CONTEXT = 'LARK_PLUGIN_CONTEXT'
export const LARK_LONG_CONNECTION_SERVICE = 'LARK_LONG_CONNECTION_SERVICE'
export const LARK_CONVERSATION_QUEUE_SERVICE = 'LARK_CONVERSATION_QUEUE_SERVICE'
