import { QwenRealtimeProtocol } from './protocol'
import type { RealtimeModelEvent } from '@xpert-ai/contracts'
const protocols: QwenRealtimeProtocol[] = []
afterEach(() => { for (const protocol of protocols.splice(0)) protocol.close() })
function fixture() {
  const events: RealtimeModelEvent[] = []
  const send = jest.fn()
  const protocol = new QwenRealtimeProtocol({ voice: 'Tina', instructions: 'Talk', tools: [] }, { send, emit: (event) => events.push(event) })
  protocols.push(protocol)
  const ack = () => {
    const sent = send.mock.calls.filter(([event]) => event.item?.type === 'message').at(-1)[0]
    protocol.receive({ type: 'conversation.item.created', item: { ...sent.item, id: 'server-replaced-id', status: 'completed' } })
  }
  const ackTool = (id: string) => protocol.receive({ type: 'conversation.item.created', item: {
    type: 'function_call_output', call_id: id, status: 'completed'
  } })
  const completeTools = (responseId: string, ids: string[]) => protocol.receive({ type: 'response.done', response: {
    id: responseId, status: 'completed', output: ids.map(id => ({ type: 'function_call', status: 'completed',
      call_id: id, name: 'delegate_task', arguments: '{"goal":"test"}' }))
  } })
  return { protocol, send, events, ack, ackTool, completeTools }
}
describe('Qwen realtime wire protocol', () => {
  it('fails explicitly when runtime data is not acknowledged instead of speaking stale state', () => {
    jest.useFakeTimers()
    const { protocol, send, events } = fixture()
    try {
      protocol.receive({ type: 'session.updated' })
      protocol.notify('Finished')
      jest.advanceTimersByTime(10000)
      expect(events.at(-1)).toEqual({ type: 'error', code: 'context_ack_timeout' })
      expect(send.mock.calls.some(([event]) => event.type === 'response.create')).toBe(false)
    } finally { protocol.close(); jest.useRealTimers() }
  })

  it('defers silent task context until the active response completes without starting another response', () => {
    const { protocol, send, ack } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'response.created', response: { id: 'speaking' } })
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'completed', result: 'Found it' }])
    expect(send).not.toHaveBeenCalled()
    protocol.receive({ type: 'response.done', response: { id: 'speaking' } })
    ack()
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create'])
  })

  it('retains completed task data after notification and later speech without changing system instructions', () => {
    const { protocol, send, events, ack } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'running' }])
    ack()
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'completed', result: 'Verified https://example.org' }])
    ack()
    expect(protocol.notify('Completed')).toBe(true)
    ack()
    protocol.receive({ type: 'response.created', response: { id: 'announcement' } })
    protocol.receive({ type: 'response.done', response: { id: 'announcement' } })
    protocol.receive({ type: 'input_audio_buffer.speech_started' })
    protocol.receive({ type: 'input_audio_buffer.speech_stopped' })
    protocol.receive({ type: 'response.created', response: { id: 'followup' } })
    protocol.receive({ type: 'response.done', response: { id: 'followup' } })
    const snapshots = send.mock.calls.filter(([event]) => event.item?.type === 'message')
      .map(([event]) => JSON.parse(event.item.content[0].text.slice('[XPERT_RUNTIME] '.length)))
    expect(snapshots.map(item => item.kind)).toEqual(['task_snapshot', 'task_snapshot', 'task_completion'])
    expect(JSON.parse(snapshots[1].payload)).toEqual([{ taskHandle: 'task', status: 'completed', result: 'Verified https://example.org' }])
    expect(send.mock.calls.some(([event]) => event.type === 'session.update')).toBe(false)
    expect(events.some(event => event.type === 'transcript' && event.role === 'user')).toBe(false)
  })

  it('coalesces task changes and waits for the exact acknowledgement without creating speech', () => {
    const { protocol, send, ack } = fixture()
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'queued' }])
    expect(send).not.toHaveBeenCalled()
    protocol.receive({ type: 'session.updated' })
    expect(send).toHaveBeenCalledTimes(1)
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'running' }])
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'completed', result: 'Found it' }])
    protocol.receive({ type: 'conversation.item.created', item: { id: 'unrelated', type: 'message', role: 'user', content: [{ type: 'input_text', text: 'Other input' }] } })
    expect(send).toHaveBeenCalledTimes(1)
    ack()
    ack()
    protocol.updateTaskContext([{ taskHandle: 'task', status: 'completed', result: 'Found it' }])
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create', 'conversation.item.create'])
  })

  it('waits for acknowledged audio configuration before capture', () => {
    const { protocol, send, events } = fixture()
    protocol.appendAudio(new Uint8Array(640))
    expect(send).not.toHaveBeenCalled()
    protocol.receive({ type: 'session.created' })
    expect(send.mock.calls[0][0].session.audio.input.format.sample_rate).toBe(16000)
    protocol.receive({ type: 'session.updated' })
    expect(events).toContainEqual({ type: 'ready' })
    protocol.appendAudio(new Uint8Array(640))
    expect(send.mock.calls.at(-1)[0].type).toBe('input_audio_buffer.append')
    protocol.setMuted(true)
    send.mockClear()
    protocol.appendAudio(new Uint8Array(640))
    expect(send).not.toHaveBeenCalled()
  })
  it('executes confirmed calls once and waits for all output acknowledgements before continuing', () => {
    const { protocol, send, events, completeTools, ackTool } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    for (const id of ['c1', 'c2']) protocol.receive({ type: 'response.function_call_arguments.done', call_id: id, name: 'delegate_task', arguments: '{"goal":"test"}' })
    expect(events.some(event => event.type === 'tools')).toBe(false)
    completeTools('r1', ['c1', 'c2'])
    expect(events.filter(event => event.type === 'tools')).toHaveLength(1)
    protocol.submitToolResults([{ id: 'c1', output: 'accepted' }])
    expect(send).not.toHaveBeenCalled()
    protocol.submitToolResults([{ id: 'c2', output: 'accepted' }])
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create', 'conversation.item.create'])
    ackTool('unknown')
    ackTool('c1')
    expect(send).toHaveBeenCalledTimes(2)
    ackTool('c2')
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create', 'conversation.item.create', 'response.create'])
    protocol.submitToolResults([{ id: 'c1', output: 'duplicate' }])
    completeTools('r1', ['c1', 'c2'])
    ackTool('c2')
    expect(send).toHaveBeenCalledTimes(3)
    expect(events.filter(event => event.type === 'tools')).toHaveLength(1)
  })
  it('suppresses canceled response audio while allowing the next turn', () => {
    const { protocol, send, events } = fixture()
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    protocol.receive({ type: 'input_audio_buffer.speech_started' })
    protocol.receive({ type: 'response.audio.delta', response_id: 'r1', delta: 'AAA=' })
    expect(events.some((event) => event.type === 'audio')).toBe(false)
    expect(send).not.toHaveBeenCalledWith(expect.objectContaining({ type: 'response.cancel' }))
    protocol.receive({ type: 'input_audio_buffer.speech_stopped' })
    protocol.receive({ type: 'response.created', response: { id: 'r2' } })
    protocol.receive({ type: 'response.audio.delta', response_id: 'r2', delta: 'AAA=' })
    expect(events.filter((event) => event.type === 'audio')).toHaveLength(1)
  })
  it('reports provider usage and does not fabricate proactive input events', () => {
    const { protocol, send, events } = fixture()
    protocol.receive({ type: 'response.done', response: { id: 'r', usage: { input_tokens_details: { text_tokens: 3, audio_tokens: 7 }, output_tokens_details: { text_tokens: 2, audio_tokens: 8 } } } })
    expect(events).toContainEqual({ type: 'usage', usage: { responseId: 'r', inputText: 3, inputAudio: 7, outputText: 2, outputAudio: 8 } })
    expect(protocol.notify('finished')).toBe(false)
    expect(send).not.toHaveBeenCalled()
  })
  it('waits for result-message acknowledgement and emits no fabricated user transcript', () => {
    const { protocol, send, events, ack } = fixture()
    protocol.receive({ type: 'session.updated' })
    expect(protocol.notify('Found the source')).toBe(true)
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create'])
    expect(send.mock.calls[0][0].item.content[0].text).toContain('Found the source')
    expect(protocol.notify('Duplicate')).toBe(false)
    ack()
    expect(send.mock.calls.at(-1)[0].type).toBe('response.create')
    protocol.receive({ type: 'response.created', response: { id: 'notification' } })
    protocol.receive({ type: 'response.done', response: { id: 'notification' } })
    expect(send).toHaveBeenCalledTimes(2)
    expect(events.filter(event => event.type === 'ready')).toHaveLength(1)
    expect(events.some(event => event.type === 'transcript' && event.role === 'user')).toBe(false)
  })

  it('lets a user turn consume an acknowledged notification without a duplicate response', () => {
    const { protocol, send, ack } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'input_audio_buffer.speech_started' })
    expect(protocol.notify('Not now')).toBe(false)
    protocol.receive({ type: 'input_audio_buffer.speech_stopped' })
    expect(protocol.notify('Wait for the VAD response')).toBe(false)
    protocol.receive({ type: 'response.created', response: { id: 'vad' } })
    protocol.receive({ type: 'response.done', response: { id: 'vad' } })
    expect(protocol.notify('Done')).toBe(true)
    protocol.receive({ type: 'input_audio_buffer.speech_started' })
    ack()
    expect(send.mock.calls.some(([event]) => event.type === 'response.create')).toBe(false)
    protocol.receive({ type: 'input_audio_buffer.speech_stopped' })
    protocol.receive({ type: 'response.created', response: { id: 'next-vad' } })
    protocol.receive({ type: 'response.done', response: { id: 'next-vad' } })
    expect(send.mock.calls.map(([event]) => event.type)).toEqual(['conversation.item.create'])
  })

  it('reserves a response before its acknowledgement so task notifications cannot start a second response', () => {
    const { protocol, send, completeTools, ackTool } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    protocol.receive({ type: 'response.function_call_arguments.done', call_id: 'c1', name: 'delegate_task', arguments: '{}' })
    completeTools('r1', ['c1'])
    protocol.submitToolResults([{ id: 'c1', output: 'accepted' }])
    ackTool('c1')
    expect(protocol.notify('Finished')).toBe(false)
    protocol.receive({ type: 'session.updated' })
    expect(send.mock.calls.filter(([event]) => event.type === 'response.create')).toHaveLength(1)
    protocol.receive({ type: 'response.created', response: { id: 'r2' } })
    protocol.receive({ type: 'response.done', response: { id: 'r2' } })
    expect(protocol.notify('Finished')).toBe(true)
  })

  it('does not execute unconfirmed calls from an interrupted response', () => {
    const { protocol, send, events } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    protocol.receive({ type: 'response.function_call_arguments.done', call_id: 'c1', name: 'delegate_task', arguments: '{}' })
    protocol.receive({ type: 'input_audio_buffer.speech_started' })
    protocol.receive({ type: 'response.done', response: { id: 'r1', status: 'cancelled' } })
    protocol.submitToolResults([{ id: 'c1', output: 'accepted' }])
    protocol.receive({ type: 'input_audio_buffer.speech_stopped' })
    expect(send).not.toHaveBeenCalled()
    expect(events.some(event => event.type === 'tools')).toBe(false)
    protocol.receive({ type: 'response.created', response: { id: 'r2' } })
    protocol.receive({ type: 'response.done', response: { id: 'r2' } })
    expect(send).not.toHaveBeenCalled()
  })

  it('keeps a harmless explicit cancellation race recoverable and strips provider free text', () => {
    const { protocol, send, events } = fixture()
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    protocol.cancelResponse()
    protocol.cancelResponse()
    expect(send).toHaveBeenCalledTimes(1)
    protocol.receive({ type: 'response.done', response: { id: 'r1' } })
    protocol.receive({ type: 'error', event_id: 'error-1', error: { type: 'invalid_request_error',
      code: 'response_cancel_not_active', event_id: send.mock.calls[0][0].event_id, message: 'secret transcript and key' } })
    expect(events.at(-1)).toEqual({ type: 'error', code: 'provider_error', recoverable: true,
      diagnostic: { providerCode: 'response_cancel_not_active', providerType: 'invalid_request_error', eventId: 'error-1' } })
    expect(JSON.stringify(events)).not.toContain('secret')
  })

  it.each(['invalid_value', 'authentication_failed', 'rate_limit_exceeded'])('does not swallow %s errors', (code) => {
    const { protocol, events } = fixture()
    protocol.receive({ type: 'error', error: { type: 'invalid_request_error', code, message: 'private input' } })
    expect(events.at(-1)).toMatchObject({ type: 'error', recoverable: false, diagnostic: { providerCode: code } })
  })

  it('waits for the existing response after a create conflict instead of retrying in a loop', () => {
    const { protocol, send, events, ack } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.notify('Completed')
    ack()
    protocol.receive({ type: 'error', error: { type: 'invalid_request_error', code: 'conversation_already_has_active_response' } })
    expect(events.at(-1)).toMatchObject({ recoverable: true })
    expect(protocol.notify('Other completion')).toBe(false)
    expect(send.mock.calls.filter(([event]) => event.type === 'response.create')).toHaveLength(1)
  })

  it('reports response failure diagnostics and never starts queued work after closing', () => {
    const { protocol, send, events } = fixture()
    protocol.receive({ type: 'session.updated' })
    protocol.receive({ type: 'response.created', response: { id: 'r1' } })
    protocol.receive({ type: 'response.done', response: { id: 'r1', status: 'failed',
      status_details: { error: { type: 'server_error', code: 'internal_error' } } } })
    expect(events.at(-1)).toMatchObject({ type: 'error', recoverable: false, diagnostic: { providerCode: 'internal_error' } })
    protocol.close()
    expect(protocol.notify('Late result')).toBe(false)
    expect(send).not.toHaveBeenCalled()
  })
})
