import { Injectable } from '@nestjs/common'
import { dispatchCustomEvent } from '@langchain/core/callbacks/dispatch'
import { tool } from '@langchain/core/tools'
import { ChatMessageEventTypeEnum, ChatMessageStepCategory, TAgentMiddlewareMeta } from '@xpert-ai/contracts'
import {
  AgentMiddleware,
  AgentMiddlewareStrategy,
  IAgentMiddlewareContext,
  IAgentMiddlewareStrategy,
  PromiseOrValue,
  RequestContext
} from '@xpert-ai/plugin-sdk'
import { z } from 'zod/v3'
import {
  CANVAS_AGENT_CAPABILITY,
  CANVAS_CREATE_DOCUMENT_TOOL_NAME,
  CANVAS_FEATURE,
  CANVAS_GET_DOCUMENT_TOOL_NAME,
  CANVAS_GET_RECORD_TOOL_NAME,
  CANVAS_ICON,
  CANVAS_INSERT_IMAGE_TOOL_NAME,
  CANVAS_MIDDLEWARE_NAME,
  CANVAS_PATCH_RECORDS_TOOL_NAME,
  CANVAS_REPORT_FAILURE_TOOL_NAME,
  CANVAS_SAVE_SNAPSHOT_TOOL_NAME,
  CANVAS_SEARCH_DOCUMENTS_TOOL_NAME,
  CANVAS_UPDATE_DOCUMENT_STATUS_TOOL_NAME,
  CANVAS_WORKBENCH_CAPABILITY
} from './constants.js'
import {
  stringifyAgentToolResult,
  summarizeDocumentMutationResult,
  summarizeFailureResult,
  summarizeGetDocumentResult,
  summarizeGetRecordResult,
  summarizeSearchResult
} from './canvas-agent-response.js'
import { CanvasService } from './canvas.service.js'
import type { CanvasJsonObject, CanvasJsonValue, CanvasRecord, CanvasScope, CanvasSnapshotData } from './types.js'

const documentKindSchema = z.enum(['canvas', 'whiteboard', 'moodboard', 'wireframe', 'annotation', 'image-board', 'other'])
const documentStatusSchema = z.enum(['draft', 'reviewed', 'archived'])
const versionSourceSchema = z.enum(['agent_snapshot', 'agent_patch', 'agent_image', 'workbench', 'import', 'restore'])
const jsonValueSchema: z.ZodType<CanvasJsonValue> = z.lazy(() =>
  z.union([z.string(), z.number(), z.boolean(), z.null(), z.array(jsonValueSchema), z.record(jsonValueSchema)])
)
const recordSchema = z.record(jsonValueSchema) as z.ZodType<CanvasJsonObject>
const canvasRecordSchema = z.object({ id: z.string().min(1) }).catchall(jsonValueSchema) as z.ZodType<CanvasRecord>
const snapshotSchema = z.object({
  schema: jsonValueSchema.describe('tldraw store schema from editor.store.getStoreSnapshot().schema.'),
  store: z.record(canvasRecordSchema).describe('tldraw records keyed by record id.')
}) as z.ZodType<CanvasSnapshotData>
const snapshotImageSchema = z.object({
  dataUrl: z.string().optional().describe('PNG/JPEG/WebP image data URL for the rendered Canvas viewport.'),
  base64: z.string().optional().describe('Raw PNG/JPEG/WebP base64 when dataUrl is omitted.'),
  mimeType: z.enum(['image/png', 'image/jpeg', 'image/webp']).optional(),
  fileName: z.string().optional(),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional(),
  pageId: z.string().optional(),
  camera: jsonValueSchema.optional(),
  capturedAt: z.string().optional()
})

const createDocumentSchema = z.object({
  title: z.string().min(1).describe('Human-readable canvas title.'),
  description: z.string().optional(),
  kind: documentKindSchema.optional(),
  tags: z.array(z.string()).optional(),
  source: z.string().optional().describe('Short source label, such as user_request, imported_file, or agent_plan.'),
  snapshot: snapshotSchema.optional().describe('Optional complete tldraw snapshot for the initial version. Usually omit, then save in stages.'),
  viewState: recordSchema.optional(),
  selectionSummary: recordSchema.optional(),
  snapshotImage: snapshotImageSchema.optional().describe('Optional rendered viewport image. Workbench normally supplies this; Agents may omit it.'),
  changeSummary: z.string().optional()
})

const saveSnapshotSchema = z.object({
  documentId: z.string().min(1).describe('Existing Canvas document id.'),
  snapshot: snapshotSchema.describe('Complete tldraw snapshot from the Canvas Workbench or generated by the Agent.'),
  viewState: recordSchema.optional(),
  selectionSummary: recordSchema.optional(),
  snapshotImage: snapshotImageSchema.optional().describe('Optional rendered viewport image. When supplied, the backend stores a version snapshot image file.'),
  sourceType: versionSourceSchema.optional(),
  changeSummary: z.string().optional()
})

const patchRecordsSchema = z.object({
  documentId: z.string().min(1),
  putRecords: z.array(recordSchema).optional().describe('Full tldraw records to insert or replace, each with an id.'),
  removeRecordIds: z.array(z.string()).optional().describe('Existing tldraw record ids to remove.'),
  viewStatePatch: recordSchema.optional().describe('Shallow view state patch.'),
  selectionSummary: recordSchema.optional().describe('Optional new selection summary for Workbench context.'),
  changeSummary: z.string().optional()
})

const insertionTargetSchema = z.object({
  documentId: z.string().optional().describe('Canvas document id copied from env.canvasInsertionTargetJson when present.'),
  pageId: z.string().optional().describe('Target tldraw page id. Usually copied from env.canvasInsertionTargetJson.'),
  shapeId: z.string().optional().describe('Selected shape id or AI image holder id. The backend infers holder fill behavior.'),
  width: z.number().int().positive().optional().describe('Desired display width. Usually copied from the selected holder.'),
  height: z.number().int().positive().optional().describe('Desired display height. Usually copied from the selected holder.')
})

const insertImageSchema = z.object({
  documentId: z.string().optional().describe('Existing Canvas document id. Prefer env.canvasDocumentId. Required unless target.documentId is provided.'),
  workspaceFilePath: z.string().optional().describe('Workspace image path returned by an image generation tool. If the tool says workspacePath or filePath, pass that value here.'),
  dataUrl: z.string().optional().describe('Image data URL when the image is already inline.'),
  base64: z.string().optional().describe('Raw image base64 when dataUrl/workspaceFilePath is unavailable.'),
  mimeType: z.string().optional().describe('Image MIME type for base64. Defaults to image/png.'),
  target: insertionTargetSchema.optional().describe('Optional compact target copied from env.canvasInsertionTargetJson.'),
  changeSummary: z.string().optional().describe('Short user-facing summary shown as the tool call title.')
})

const searchDocumentsSchema = z.object({
  status: documentStatusSchema.optional(),
  kind: documentKindSchema.optional(),
  search: z.string().optional(),
  page: z.number().int().min(1).optional(),
  pageSize: z.number().int().min(1).max(100).optional()
})

const getDocumentSchema = z.object({
  documentId: z.string().min(1),
  versionId: z.string().optional(),
  versionNumber: z.number().int().min(1).optional(),
  includeSnapshot: z.boolean().optional().describe('Set true only when full tldraw snapshot JSON is required.'),
  versionLimit: z.number().int().min(1).max(100).optional(),
  includeLogs: z.boolean().optional(),
  logLimit: z.number().int().min(1).max(50).optional()
})

const getRecordSchema = z.object({
  documentId: z.string().min(1),
  recordId: z.string().min(1),
  versionId: z.string().optional(),
  versionNumber: z.number().int().min(1).optional()
})

const updateDocumentStatusSchema = z.object({
  documentId: z.string().min(1),
  status: documentStatusSchema,
  reason: z.string().optional()
})

const reportFailureSchema = z.object({
  documentId: z.string().optional(),
  versionId: z.string().optional(),
  operation: z.string().min(1),
  errorMessage: z.string().min(1),
  recoverable: z.boolean().optional(),
  evidence: jsonValueSchema.optional()
})

const CHANGE_SUMMARY_EVENT_TOOL_NAMES = new Set([
  CANVAS_CREATE_DOCUMENT_TOOL_NAME,
  CANVAS_SAVE_SNAPSHOT_TOOL_NAME,
  CANVAS_PATCH_RECORDS_TOOL_NAME,
  CANVAS_INSERT_IMAGE_TOOL_NAME
])

@Injectable()
@AgentMiddlewareStrategy(CANVAS_MIDDLEWARE_NAME)
export class CanvasMiddleware implements IAgentMiddlewareStrategy<Record<string, never>> {
  readonly meta: TAgentMiddlewareMeta = {
    name: CANVAS_MIDDLEWARE_NAME,
    label: {
      en_US: 'Canvas',
      zh_Hans: 'Canvas 画布'
    },
    description: {
      en_US: 'Create, update, version, search, annotate, and recover tldraw canvases from an Agent.',
      zh_Hans: '让 Agent 创建、更新、版本化、检索、标注和恢复 tldraw 画布。'
    },
    icon: {
      type: 'svg',
      value: CANVAS_ICON,
      color: '#0f766e'
    },
    features: [CANVAS_FEATURE, CANVAS_AGENT_CAPABILITY, CANVAS_WORKBENCH_CAPABILITY],
    configSchema: {
      type: 'object',
      properties: {},
      required: []
    }
  }

  constructor(private readonly service: CanvasService) {}

  createMiddleware(_options: Record<string, never>, context: IAgentMiddlewareContext): PromiseOrValue<AgentMiddleware> {
    const scope = scopeFromContext(context)

    return {
      name: CANVAS_MIDDLEWARE_NAME,
      tools: [
        tool(
          async (input) => stringifyAgentToolResult(summarizeDocumentMutationResult(await this.service.createDocument(scope, input), 'Canvas document was created.')),
          {
            name: CANVAS_CREATE_DOCUMENT_TOOL_NAME,
            description:
              'Create a reviewable Canvas document record only when there is no current Workbench canvas or the user explicitly asks for a new canvas. If env.canvasDocumentId is present, do not call this tool for image insertion; use that existing documentId instead.',
            schema: createDocumentSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeDocumentMutationResult(await this.service.saveSnapshot(scope, input), 'Canvas snapshot was saved.')),
          {
            name: CANVAS_SAVE_SNAPSHOT_TOOL_NAME,
            description:
              'Save a complete tldraw snapshot as a new Canvas version. Use this only for intentional full-canvas creation, import, or replacement; do not call it after canvas_insert_image unless you have a complete valid snapshot.',
            schema: saveSnapshotSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeDocumentMutationResult(await this.service.patchRecords(scope, input), 'Canvas records were patched.')),
          {
            name: CANVAS_PATCH_RECORDS_TOOL_NAME,
            description:
              'Patch the current Canvas working copy by inserting/replacing full tldraw records and/or removing record ids. This does not create a version. Call canvas_get_document or canvas_get_record first when changing an existing user-edited canvas.',
            schema: patchRecordsSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeDocumentMutationResult(await this.service.insertImage(scope, input), 'Image was inserted into the canvas.')),
          {
            name: CANVAS_INSERT_IMAGE_TOOL_NAME,
            description:
              'Insert one generated bitmap into the current Canvas working copy. This does not create a version. Use documentId from env.canvasDocumentId or target.documentId from env.canvasInsertionTargetJson. Pass exactly one image source: workspaceFilePath, dataUrl, or base64. If env.canvasInsertionTargetJson is present, parse it and pass it as target; the backend infers page, selected holder, size, and replacement behavior. Do not create a new canvas for image insertion.',
            schema: insertImageSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeSearchResult(await this.service.searchDocuments(scope, input))),
          {
            name: CANVAS_SEARCH_DOCUMENTS_TOOL_NAME,
            description: 'Search existing Canvas documents by status, kind, keyword, and pagination. Returns document metadata only.',
            schema: searchDocumentsSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeGetDocumentResult(await this.service.getDocument(scope, input), input.includeSnapshot)),
          {
            name: CANVAS_GET_DOCUMENT_TOOL_NAME,
            description:
              'Get Canvas metadata, working-copy scene by default, current version metadata, optional logs, and optional full tldraw snapshot. Leave includeSnapshot false unless exact record JSON is needed. If snapshotImagePath is present, call view_image with that path before visual analysis.',
            schema: getDocumentSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeGetRecordResult(await this.service.getRecordForAgent(scope, input))),
          {
            name: CANVAS_GET_RECORD_TOOL_NAME,
            description:
              'Fetch one exact tldraw record from the Canvas working copy by default, or from a requested versionId/versionNumber. Use this before targeted edits to selected shapes, assets, bindings, pages, or image holders.',
            schema: getRecordSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeDocumentMutationResult(await this.service.updateDocumentStatus(scope, input), 'Canvas status was updated.')),
          {
            name: CANVAS_UPDATE_DOCUMENT_STATUS_TOOL_NAME,
            description: 'Update a Canvas document status to draft, reviewed, or archived after user confirmation.',
            schema: updateDocumentStatusSchema,
            verboseParsingErrors: true
          }
        ),
        tool(
          async (input) => stringifyAgentToolResult(summarizeFailureResult(await this.service.reportFailure(scope, input))),
          {
            name: CANVAS_REPORT_FAILURE_TOOL_NAME,
            description:
              'Record a failed Canvas generation, snapshot validation, image insertion, import, or patch attempt with recoverability and evidence.',
            schema: reportFailureSchema,
            verboseParsingErrors: true
          }
        )
      ],
      wrapToolCall: async (request, handler) => {
        const changeSummary = readChangeSummaryMessage(request.toolCall.args)
        if (!changeSummary || !CHANGE_SUMMARY_EVENT_TOOL_NAMES.has(request.toolCall.name)) {
          return handler(request)
        }

        const createdAt = new Date()
        await dispatchCanvasToolStepEvent({
          request,
          message: changeSummary,
          status: 'running',
          createdAt
        })

        try {
          const result = await handler(request)
          await dispatchCanvasToolStepEvent({
            request,
            message: changeSummary,
            status: 'success',
            createdAt
          })
          return result
        } catch (error) {
          await dispatchCanvasToolStepEvent({
            request,
            message: changeSummary,
            status: 'fail',
            createdAt,
            error: getErrorMessage(error instanceof Error ? error : String(error))
          })
          throw error
        }
      }
    }
  }
}

function scopeFromContext(context: IAgentMiddlewareContext): CanvasScope {
  return {
    tenantId: context.tenantId,
    organizationId: context.organizationId === undefined ? RequestContext.getOrganizationId() : context.organizationId,
    workspaceId: context.workspaceId ?? null,
    projectId: context.projectId ?? null,
    userId: context.userId,
    conversationId: context.conversationId ?? null,
    assistantId: context.xpertId ?? null
  }
}

type ToolArgsValue = CanvasJsonValue | object | null | undefined

function readChangeSummaryMessage(args: ToolArgsValue) {
  if (!isPlainObject(args)) {
    return undefined
  }
  const value = args.changeSummary
  return typeof value === 'string' && value.trim() ? value.trim() : undefined
}

type CanvasToolStepStatus = 'running' | 'success' | 'fail'

async function dispatchCanvasToolStepEvent({
  request,
  message,
  status,
  createdAt,
  error
}: {
  request: Parameters<NonNullable<AgentMiddleware['wrapToolCall']>>[0]
  message: string
  status: CanvasToolStepStatus
  createdAt: Date
  error?: string
}) {
  const toolCall = request.toolCall
  const runtimeMetadata = request.runtime && typeof request.runtime === 'object'
    ? Reflect.get(request.runtime, 'metadata')
    : undefined
  const metadata = isPlainObject(runtimeMetadata) ? runtimeMetadata : {}
  const toolName = toolCall.name
  const toolCallId = getToolCallDisplayId(toolCall)
  const toolset = readStringField(metadata, ['toolset']) ?? CANVAS_MIDDLEWARE_NAME
  const toolsetId = readStringField(metadata, ['toolsetId'])
  const title = readStringField(metadata, ['toolName', toolName]) ?? toolName
  const payload = {
    id: toolCallId,
    tool_call_id: toolCall.id,
    category: 'Tool',
    type: ChatMessageStepCategory.Program,
    toolset,
    ...(toolsetId ? { toolset_id: toolsetId } : {}),
    tool: toolName,
    title,
    message,
    status,
    created_date: createdAt,
    input: toolCall.args,
    ...(status === 'running' ? { end_date: null } : { end_date: new Date() }),
    ...(error ? { error } : {})
  }
  try {
    await dispatchCustomEvent(ChatMessageEventTypeEnum.ON_TOOL_MESSAGE, payload)
  } catch (error) {
    console.warn('[CanvasMiddleware] dispatch tool message failed:', getErrorMessage(error instanceof Error ? error : String(error)))
  }
}

function getToolCallDisplayId(toolCall: { id?: string; name: string; args?: ToolArgsValue }) {
  if (typeof toolCall.id === 'string' && toolCall.id.trim()) {
    return toolCall.id.trim()
  }
  return `${toolCall.name}:${stringifyValue(toolCall.args)}`
}

function stringifyValue(value: ToolArgsValue) {
  if (typeof value === 'string') {
    return value
  }
  if (value == null) {
    return ''
  }
  try {
    return JSON.stringify(value)
  } catch {
    return String(value)
  }
}

function readStringField(record: CanvasJsonObject, keys: string[]) {
  for (const key of keys) {
    const value = record[key]
    if (typeof value === 'string' && value.trim()) {
      return value.trim()
    }
  }
  return undefined
}

function getErrorMessage(error: Error | string) {
  return error instanceof Error ? error.message : stringifyValue(error) || 'Unknown error'
}

function isPlainObject(value: ToolArgsValue): value is CanvasJsonObject {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value))
}
