import assert from 'node:assert/strict'
import {test} from 'node:test'
import {EventEmitter} from 'node:events'
import {createMysqlWorkbench,type QueryConfig,type MysqlWireDriver} from '../../../databases/mysql/dist/lib/mysql-workbench.js'
import {createDorisStreamLoad,parseStreamLoadReceipt} from '../../../databases/mysql/dist/lib/doris-stream-load.js'
const mockOptions={host:'mock.invalid',port:3306,username:'mock',password:'mock',catalog:'analytics'}
function wire(mode='STRICT_TRANS_TABLES'){
 const calls:QueryConfig[]=[],state={closed:0}
 const driver:MysqlWireDriver={destroy:()=>{state.closed++},query:(config)=>{calls.push(config);const events=new EventEmitter();queueMicrotask(()=>{
 const rows=config.sql.includes('@@session.sql_mode')?[[mode]]:config.sql.includes('@@version_comment')?[['doris-3.0.8']]:config.sql.includes('version()')?[['8.0.36']]:config.sql.includes('_db_studio_page')?[['9007199254740993','0.12345678901234567890']]:[]
 if(rows.length){events.emit('fields',rows[0].map(()=>({name:'duplicate',type:246})));for(const row of rows){row.forEach((value)=>config.typeCast({type:'NEWDECIMAL',string:()=>value,buffer:()=>null}));events.emit('result',{})}}else events.emit('result',{affectedRows:1});events.emit('end')
 });return events}}
 return{driver,calls,state}
}
for(const engine of ['mysql','doris'] as const)test(`${engine} wire preserves duplicate aliases and precision before object mapping`,async()=>{const mock=wire(),adapter=createMysqlWorkbench(mockOptions,engine,mock.driver);const result=await adapter.query({database:'analytics',mode:'read',sql:'SELECT ? AS duplicate, ? AS duplicate',parameters:["x'\\attack",'0.12345678901234567890']});assert.deepEqual(result.rows,[['9007199254740993','0.12345678901234567890']]);assert.deepEqual(result.columns.map((c)=>c.id),['c0','c1']);const call=mock.calls.find((c)=>c.sql.includes('_db_studio_page'));assert.deepEqual(call?.values,["x'\\attack",'0.12345678901234567890']);await adapter.close();assert.equal(mock.state.closed,1)})
test('text-protocol parameters fail closed in NO_BACKSLASH_ESCAPES mode',async()=>{const mock=wire('NO_BACKSLASH_ESCAPES'),adapter=createMysqlWorkbench(mockOptions,'mysql',mock.driver);await assert.rejects(()=>adapter.query({mode:'read',sql:'SELECT ?',parameters:["quoted'value"]}),/sql_mode_unsupported/);assert.equal(mock.calls.filter((c)=>c.sql.includes('_db_studio_page')).length,0);await adapter.close()})
test('driver timeout destroys only its own physical connection',async()=>{const emitter=new EventEmitter(),state={closed:0};const driver:MysqlWireDriver={query:()=>emitter,destroy:()=>{state.closed++}};const adapter=createMysqlWorkbench(mockOptions,'doris',driver);await assert.rejects(()=>adapter.query({mode:'read',sql:'SELECT 1',timeoutMs:5}),/timeout/);assert.equal(state.closed,1)})
const loadInput={database:'analytics',table:'orders',columns:['id'],rows:[['9007199254740993']],operationId:'stable-operation-123'}
test('Stream Load keeps stable labels and does not replay publish timeout',async()=>{const original=globalThis.fetch,labels:string[]=[];globalThis.fetch=async(_url,options)=>{labels.push(String((options?.headers as Record<string,string>).label));return new Response(JSON.stringify({Status:'Publish Timeout'}),{status:200})};try{const load=createDorisStreamLoad({...mockOptions,host:'fe.invalid'});assert.equal((await load(loadInput)).outcome,'pending');assert.equal((await load(loadInput)).outcome,'pending');assert.equal(labels.length,2);assert.equal(labels[0],labels[1])}finally{globalThis.fetch=original}})
test('Stream Load never forwards credentials to an unlisted redirect host',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response('',{status:307,headers:{location:'http://outside.invalid:8040/api/analytics/orders/_stream_load'}})};try{const load=createDorisStreamLoad({...mockOptions,host:'fe.invalid'});assert.equal((await load(loadInput)).outcome,'unknown');assert.equal(calls,1)}finally{globalThis.fetch=original}})
test('Stream Load accepts a configured BE redirect and retains filtered row evidence',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return calls===1?new Response('',{status:307,headers:{location:'http://be.invalid:8040/api/analytics/orders/_stream_load'}}):new Response(JSON.stringify({Status:'Success',NumberLoadedRows:1,NumberFilteredRows:1}),{status:200})};try{const options={...mockOptions,host:'fe.invalid',streamLoadHosts:['be.invalid']};const load=createDorisStreamLoad(options);const receipt=await load(loadInput);assert.equal(receipt.filteredRows,1);assert.ok(receipt.diagnostics.includes('filtered_rows_reported'));assert.equal(calls,2)}finally{globalThis.fetch=original}})
test('a success response without row counts never invents zero counts',()=>assert.throws(()=>parseStreamLoadReceipt({Status:'Success'},'mock'),/count/))
