import React from 'react';

const canvasContract={designWidth:1920,designHeight:1080,rootMode:'fill-parent',backgroundMode:'opaque'};
const controls=(tone,mediaMax=0)=>[
  {key:'tone',label:'画布明暗',type:'select',default:tone,options:[{value:'dark',label:'深橄榄'},{value:'light',label:'冷灰白'}],effect:{scope:'global',targets:['canvas','surface','typography'],minChangedRatio:.15,minRegions:8}},
  {key:'showOrnament',label:'结构标记',type:'toggle',default:true,effect:{scope:'component',targets:['ornament'],minChangedRatio:.01,minRegions:1}},
  ...(mediaMax?[{key:'imageCount',label:'图片数量',type:'range',min:0,max:mediaMax,default:mediaMax,effect:{scope:'section',targets:['media','layout'],minChangedRatio:.01,minRegions:2}}]:[])
];
const mediaSlot=max=>({field:'images',presetProp:'props.images',countKey:'imageCount',acceptedKinds:['image'],max,canPresetMedia:true});
const pal=t=>t==='light'?{bg:'#ECECEC',fg:'#10110E',muted:'#666A61',surface:'#FFFFFF',accent:'#667553',line:'#BFC2B9'}:{bg:'#2D3423',fg:'#F3F3ED',muted:'#C4C8BC',surface:'#59684A',accent:'#74805E',line:'#737B68'};
function Node({color}){return <span style={{width:34,height:34,borderRadius:'50%',background:color,display:'grid',placeItems:'center',flex:'0 0 auto'}}><i style={{width:9,height:9,borderRadius:'50%',background:'#F3F3ED'}}/></span>}
function RuleTitle({children,size=76}){return <div><h1 style={{margin:0,fontSize:size,lineHeight:1.04,letterSpacing:'-.055em',whiteSpace:'pre-line',fontWeight:950}}>{children}</h1><i style={{display:'block',width:130,height:6,background:'currentColor',marginTop:26}}/></div>}
function Media({src,c,style}){return <div style={{overflow:'hidden',borderRadius:14,background:'linear-gradient(135deg,'+c.fg+' 0 12%,'+c.bg+' 12% 28%,'+c.line+' 28% 38%,'+c.fg+' 38% 53%,'+c.surface+' 53% 72%,'+c.bg+' 72%)',filter:'grayscale(1)',...style}}>{src&&<img src={typeof src==='string'?src:src.src} alt="" style={{width:'100%',height:'100%',objectFit:'cover',filter:'grayscale(1) contrast(1.08)'}}/>}</div>}
function ThemePage(props){const {variant,family,tone='dark',showOrnament=true}=props,c=pal(tone),imageCount=props.imageCount??9,images=(props.images||[]).slice(0,imageCount),media=images[0]||props.media,baseBg=imageCount===0?c.surface:c.bg,canvasBg=showOrnament?'linear-gradient(135deg,'+baseBg+' 0 88%,'+c.accent+' 88% 100%)':baseBg;const root={width:'100%',height:'100%',position:'relative',overflow:'hidden',boxSizing:'border-box',background:canvasBg,color:c.fg,fontFamily:'Inter, PingFang SC, sans-serif',padding:58};const mark=showOrnament?<div style={{position:'absolute',right:54,bottom:42}}><Node color={c.accent}/></div>:null;
  if(family==='cover'){const alt=variant.includes('alternate');return <section style={root}>{alt?<div style={{height:'100%',display:'grid',gridTemplateColumns:'1fr .92fr',gap:52}}><div style={{display:'flex',flexDirection:'column'}}><span style={{borderTop:'1px solid '+c.line,paddingTop:16}}>{props.kicker}</span><div style={{marginTop:'auto'}}><RuleTitle size={88}>{props.title}</RuleTitle><p style={{fontSize:23,color:c.muted}}>{props.subtitle}</p></div></div><Media src={media} c={c} style={{height:'100%'}}/></div>:<div style={{height:'100%',display:'grid',gridTemplateColumns:'55% 45%',gap:34}}><div style={{display:'flex',flexDirection:'column'}}><div style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid '+c.line,paddingTop:15}}><span>{props.eyebrow}</span><span>流线规划</span></div><RuleTitle size={92}>{props.title}</RuleTitle><div style={{display:'grid',gridTemplateColumns:'280px 1fr',gap:38,alignItems:'center',marginTop:70}}><Media src={images[0]} c={c} style={{height:220}}/><p style={{fontSize:26,lineHeight:1.5}}>{props.subtitle}</p></div><div style={{display:'flex',gap:100,marginTop:'auto'}}>{(props.metrics||[]).map((x,i)=><div key={i}><span>{x.label}</span><b style={{display:'block',fontSize:42,marginTop:12}}>{x.value}</b></div>)}</div></div><Media src={images[1]} c={c} style={{height:'100%'}}/></div>}{mark}</section>}
  if(family==='metrics'){return <section style={root}><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:36}}>{(props.sections||[]).map((x,i)=><article key={i}><b style={{fontSize:30}}>0{i+1}</b><h3 style={{fontSize:24}}>{x.title}</h3><p style={{color:c.muted,lineHeight:1.5}}>{x.body}</p></article>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:58,alignItems:'end',marginTop:120}}><RuleTitle>{props.title}</RuleTitle><div style={{display:'grid',gridTemplateColumns:'180px 1fr',gap:26,background:c.surface,padding:28,borderRadius:14}}><Media src={media} c={c} style={{height:190}}/><div>{(props.metrics||[]).map((x,i)=><div key={i} style={{borderBottom:'1px solid '+c.line,padding:'8px 0'}}><b style={{fontSize:36}}>{x.value}</b><span style={{marginLeft:16}}>{x.label}</span></div>)}</div></div></div>{mark}</section>}
  if(family==='general'){return <section style={root}><RuleTitle size={66}>{props.title}</RuleTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'42px 70px',marginTop:66}}>{(props.items||[]).map((x,i)=><article key={i} style={{display:'grid',gridTemplateColumns:'42px 1fr',gap:18}}><Node color={c.accent}/><div><h3 style={{fontSize:25,margin:0}}>{x.title}</h3><p style={{fontSize:18,color:c.muted,lineHeight:1.5}}>{x.body}</p></div></article>)}</div><Media src={media} c={c} style={{position:'absolute',left:58,right:58,bottom:58,height:300}}/></section>}
  if(family==='timeline'){return <section style={root}><div style={{display:'grid',gridTemplateColumns:'620px 1fr',gap:70,height:'100%'}}><div><RuleTitle>{props.title}</RuleTitle><p style={{fontSize:21,lineHeight:1.55,color:c.muted}}>{props.body}</p><div style={{display:'flex',gap:16,alignItems:'center',marginTop:230}}><Node color={c.accent}/><b>循环经济设计</b></div></div><div style={{display:'flex',alignItems:'end',gap:26}}>{(props.stages||[]).map((x,i)=><article key={i} style={{height:320+i*140,flex:1,padding:28,borderRadius:'14px 14px 0 0',background:i===2?c.surface:(tone==='dark'?'#E3E3DF':'#D2D3CE'),color:i===2?c.fg:'#111'}}><b style={{fontSize:34}}>{x.year}</b><div style={{marginTop:180+i*80}}><h3>{x.title}</h3><p>{x.body}</p></div></article>)}</div></div></section>}
  if(family==='ranking'){return <section style={root}><div style={{display:'grid',gridTemplateColumns:'1fr 1.08fr',gap:70,height:'100%'}}><div><RuleTitle>{props.title}</RuleTitle><Media src={media} c={c} style={{height:380,marginTop:80}}/></div><div style={{paddingTop:30}}>{(props.items||[]).map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'150px 1fr',gap:24,minHeight:190,borderBottom:'1px solid '+c.line}}><b style={{fontSize:50,color:c.muted}}>{x.value}</b><div><h2 style={{fontSize:28}}>{x.title}</h2><p style={{color:c.muted}}>{x.body}</p></div></div>)}</div></div></section>}
  if(family==='media'){const facts=props.items||props.facts||[];return <section style={root}><div style={{display:'flex',justifyContent:'space-between'}}><RuleTitle size={68}>{props.title}</RuleTitle>{props.metric&&<div><b style={{fontSize:42}}>{props.metric.value}</b><p style={{color:c.muted}}>{props.metric.label}</p></div>}</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:22,marginTop:48}}>{[0,1,2,3].map((n)=><article key={n} style={{height:280,display:'grid',gridTemplateColumns:'220px 1fr',overflow:'hidden',borderRadius:14,background:n%2?c.surface:(tone==='dark'?'#F4F4F0':'#FFFFFF'),color:n%2?c.fg:'#111'}}><Media src={images[n]} c={c} style={{height:'100%',borderRadius:0}}/><div style={{padding:26}}><h3 style={{fontSize:24}}>{facts[n]?.title||facts[n]?.label||'案例 '+(n+1)}</h3><p style={{lineHeight:1.5}}>{facts[n]?.body||facts[n]?.value||props.caption}</p></div></article>)}</div></section>}
  if(family==='comparison'){return <section style={root}><div style={{height:'100%',display:'grid',gridTemplateColumns:'1fr 1.05fr',gap:34}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{(props.cards||[]).map((x,i)=><article key={i} style={{padding:30,borderRadius:14,background:i===1?c.bg:i===2?c.accent:(tone==='dark'?'#F2F2EE':'#FFFFFF'),color:i===1?c.fg:'#111',border:'1px solid '+c.line}}><b>0{i+1}</b><h3 style={{fontSize:28,marginTop:75}}>{x.title}</h3><p style={{fontSize:18,lineHeight:1.5}}>{x.body}</p></article>)}</div><div style={{padding:'60px 0 0 45px'}}><RuleTitle>{props.title}</RuleTitle><p style={{fontSize:22,lineHeight:1.6,color:c.muted}}>{props.lead}</p><Media src={media} c={c} style={{height:340,marginTop:55}}/></div></div></section>}
  if(family==='statement'||family==='closing'){return <section style={root}><RuleTitle size={82}>{props.title}</RuleTitle><div style={{display:'grid',gridTemplateColumns:'1fr .82fr',gap:60,marginTop:70,height:610}}><div style={{display:'flex',flexDirection:'column'}}><p style={{fontSize:28,lineHeight:1.55}}>{props.statement||props.subtitle}</p><div style={{marginTop:'auto',display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}>{(props.items||[]).map((x,i)=><article key={i} style={{padding:28,borderRadius:14,background:i?c.surface:(tone==='dark'?'#F3F3EF':'#FFFFFF'),color:i?c.fg:'#111'}}><h3>{x.title}</h3><p>{x.body}</p><Node color={c.accent}/></article>)}</div><b style={{marginTop:28,fontSize:22}}>{props.action}</b></div>{media?<Media src={media} c={c} style={{height:'100%'}}/>:<div style={{background:c.surface,borderRadius:14,display:'grid',placeItems:'center'}}><Node color={c.bg}/></div>}</div></section>}
  if(family==='table'){return <section style={root}><RuleTitle size={68}>{props.title}</RuleTitle><div style={{marginTop:70,borderTop:'2px solid '+c.fg}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',padding:'20px 28px',background:c.accent,color:'#fff',fontWeight:800}}>{(props.columns||[]).map(x=><span key={x}>{x}</span>)}</div>{(props.rows||[]).map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',padding:'24px 28px',borderBottom:'1px solid '+c.line,fontSize:20}}>{r.map((x,j)=><span key={j} style={{fontWeight:j===0?800:400}}>{x}</span>)}</div>)}</div>{mark}</section>}
  if(family==='distribution'){return <section style={root}><RuleTitle size={70}>{props.title}</RuleTitle><div style={{display:'flex',alignItems:'end',gap:28,height:520,marginTop:70}}>{(props.segments||[]).map((s,i)=><article key={i} style={{flex:1,height:180+s.value*7,background:i===0?c.accent:(i%2?c.surface:(tone==='dark'?'#E3E3DF':'#CACCC6')),color:i===2?'#111':c.fg,padding:28,borderRadius:'14px 14px 0 0'}}><b style={{fontSize:48}}>{s.value}%</b><h3>{s.label}</h3></article>)}</div><p style={{fontSize:22,color:c.muted}}>{props.summary}</p></section>}
  if(family==='relationship'){return <section style={root}><RuleTitle size={70}>{props.title}</RuleTitle><div style={{position:'relative',height:640,marginTop:28}}>{(props.links||[]).map((x,i)=><i key={i} style={{position:'absolute',left:260+i*230,top:260+(i%2)*70,width:260,height:3,background:c.line,transform:'rotate('+(-15+i*10)+'deg)'}}/>)}{(props.nodes||[]).map((n,i)=><article key={n.id} style={{position:'absolute',left:100+(i%3)*520,top:80+Math.floor(i/3)*330,width:250,height:150,borderRadius:14,background:i%2?c.surface:(tone==='dark'?'#F1F1ED':c.accent),color:i%2?c.fg:(tone==='dark'?'#111':'#fff'),display:'flex',alignItems:'center',gap:20,padding:28,fontSize:25,fontWeight:850}}><Node color={i%2?c.bg:c.accent}/>{n.label}</article>)}</div></section>}
  if(family==='proportion'){return <section style={root}><RuleTitle size={70}>{props.title}</RuleTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:34,marginTop:80}}>{(props.values||[]).map((v,i)=><article key={i} style={{height:480,borderRadius:14,background:i===2?c.surface:(tone==='dark'?'#E2E2DE':'#FFFFFF'),color:i===2?c.fg:'#111',padding:32,display:'flex',flexDirection:'column'}}><b style={{fontSize:70}}>{v}%</b><div style={{marginTop:'auto',height:v*2.6,background:i===2?c.bg:c.accent,borderRadius:'10px 10px 0 0'}}/><h3>{props.labels?.[i]}</h3></article>)}</div></section>}
  if(family==='transition'){return <section style={root}><span>{props.kicker}</span><div style={{height:'82%',display:'grid',gridTemplateColumns:'1fr 420px',alignItems:'center'}}><RuleTitle size={104}>{props.title}</RuleTitle><b style={{fontSize:220,textAlign:'right',color:c.accent}}>{props.sectionNumber}</b></div><div style={{position:'absolute',left:58,right:58,bottom:55,height:2,background:c.line}}/></section>}
  return <section style={root}><RuleTitle>{props.title}</RuleTitle>{mark}</section>
}
function Signature01SplitArchitectureCover(props){return <ThemePage variant="split-architecture-cover" family="cover" {...props}/>}
function Signature02ProgramMetricOverview(props){return <ThemePage variant="program-metric-overview" family="metrics" {...props}/>}
function Signature03SixNodeProgram(props){return <ThemePage variant="six-node-program" family="general" {...props}/>}
function Signature04SteppedYearBlocks(props){return <ThemePage variant="stepped-year-blocks" family="timeline" {...props}/>}
function Signature05DetailSignalRanking(props){return <ThemePage variant="detail-signal-ranking" family="ranking" {...props}/>}
function Signature06ArchitecturalCaseGrid(props){return <ThemePage variant="architectural-case-grid" family="media" {...props}/>}
function Signature07MaterialComparisonGrid(props){return <ThemePage variant="material-comparison-grid" family="comparison" {...props}/>}
function Signature08EnvironmentSystemStatement(props){return <ThemePage variant="environment-system-statement" family="statement" {...props}/>}
function Derived01ActionTable(props){return <ThemePage variant="derived-action-table" family="table" {...props}/>}
function Derived02ClosingCall(props){return <ThemePage variant="derived-closing-call" family="closing" {...props}/>}
function Derived03CompositionBreakdown(props){return <ThemePage variant="derived-composition-breakdown" family="distribution" {...props}/>}
function Derived04EcosystemRelationship(props){return <ThemePage variant="derived-ecosystem-relationship" family="relationship" {...props}/>}
function Derived05ProportionScorecard(props){return <ThemePage variant="derived-proportion-scorecard" family="proportion" {...props}/>}
function Derived06SectionTransition(props){return <ThemePage variant="derived-section-transition" family="transition" {...props}/>}
function Derived07AlternateCover(props){return <ThemePage variant="derived-alternate-cover" family="cover" {...props}/>}
function Derived08MediaCaseStudy(props){return <ThemePage variant="derived-media-case-study" family="media" {...props}/>}
export const signaturePages=[
{key:"theme14_signature_split_architecture_cover",slot:"signature-split-architecture-cover",label:"External signature · split-architecture-cover",roles:["cover"],moduleFamily:"cover",archetypeId:"split-architecture-cover",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 15.59.29.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["左侧标题、次级媒体和指标组成多层信息区","右侧半页黑白建筑竖图建立主视觉体量","顶端细线与小字形成项目页眉"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","eyebrow":"品牌浸润 / 流线规划","title":"建筑设计","subtitle":"核心设计理念：寻求功能与形式的平衡","metrics":[{"label":"技术集成","value":"+20%"},{"label":"可持续发展","value":"230%+"}],"images":[],"imageCount":2},controls:controls("dark",2),mediaSlots:[mediaSlot(2)],Component:Signature01SplitArchitectureCover},
{key:"theme14_signature_program_metric_overview",slot:"signature-program-metric-overview",label:"External signature · program-metric-overview",roles:["metrics"],moduleFamily:"metrics",archetypeId:"program-metric-overview",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 15.59.57.png","截屏2026-07-15 16.00.20.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["上方四列说明与下方超大双行标题形成尺度对比","苔藓绿指标卡和黑白方图组合在右下区域","圆节点、直角箭头和百分比保持同一视觉语言"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"单位面积\n销售额","sections":[{"title":"核心设计","body":"环境责任与商业智慧并重。"},{"title":"关键空间","body":"覆盖建筑全生命周期。"},{"title":"用户体验","body":"让技术深入空间。"},{"title":"可持续发展","body":"以数据支持决策。"}],"metrics":[{"value":"230%+","label":"空间效率"},{"value":"+32%","label":"过渡空间"},{"value":"+10%","label":"垂直绿化"}],"images":[],"imageCount":1},controls:controls("dark",1),mediaSlots:[mediaSlot(1)],Component:Signature02ProgramMetricOverview},
{key:"theme14_signature_six_node_program",slot:"signature-six-node-program",label:"External signature · six-node-program",roles:["general"],moduleFamily:"general",archetypeId:"six-node-program",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.15.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["六个圆节点按三列两行均匀排列","每个节点包含粗体标题与两行短说明","底部横向黑白图片跨越主要网格宽度"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"空间系统目录","items":[{"title":"总部大楼","body":"商业空间的核心定义。"},{"title":"精品酒店","body":"平衡功能与形式。"},{"title":"幕墙系统","body":"打造智能互联空间。"},{"title":"探索路径","body":"组织连续体验。"},{"title":"第五立面","body":"重新理解屋顶。"},{"title":"过渡空间","body":"连接功能与情绪。"}],"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature03SixNodeProgram},
{key:"theme14_signature_stepped_year_blocks",slot:"signature-stepped-year-blocks",label:"External signature · stepped-year-blocks",roles:["timeline"],moduleFamily:"timeline",archetypeId:"stepped-year-blocks",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.26.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["三个年度块从左到右逐级升高模拟体量","灰白与苔藓绿块交替并在底部对齐","左侧保留标题、短横线、正文和圆节点说明"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"多感官体验设计","body":"以功能、材料与社会影响三条线索推进空间策略。","stages":[{"year":"2024","title":"心理影响","body":"识别尺度与光线。"},{"year":"2025","title":"社会影响","body":"验证共享关系。"},{"year":"2026","title":"材料策略","body":"统一耐久与循环。"}]},controls:controls("dark",0),Component:Signature04SteppedYearBlocks},
{key:"theme14_signature_detail_signal_ranking",slot:"signature-detail-signal-ranking",label:"External signature · detail-signal-ranking",roles:["ranking"],moduleFamily:"ranking",archetypeId:"detail-signal-ranking",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.30.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["右侧四条百分比信号按纵向列表整齐排列","左侧超大双行标题、直角箭头和方形黑白图形成对重","浅色画布使用灰色数字与近黑标题区分层级"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"设计细节\n彰显工艺","items":[{"value":"+11%","title":"停留时间","body":"功能、氛围与戏剧效果。"},{"value":"+23%","title":"交互界面","body":"完整照明方案。"},{"value":"+89%","title":"包容性环境","body":"最大化自然光。"},{"value":"+59%","title":"导视系统","body":"根据场景自动调节。"}],"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature05DetailSignalRanking},
{key:"theme14_signature_architectural_case_grid",slot:"signature-architectural-case-grid",label:"External signature · architectural-case-grid",roles:["media"],moduleFamily:"media",archetypeId:"architectural-case-grid",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.34.png","截屏2026-07-15 16.00.39.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["四张图文卡按二乘二或横幅加说明网格组织","黑白媒体与白色、苔藓绿表面交替","圆节点和超大标题负责连接案例与指标"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"联合办公空间","metric":{"value":"+37%","label":"响应环境可持续发展需求"},"items":[{"title":"预制构件","body":"缩短施工与迭代周期。"},{"title":"声学处理","body":"控制开放空间噪声。"},{"title":"参数化设计","body":"比较采光与流线。"},{"title":"耐久性测试","body":"验证高频使用表现。"}],"images":[],"imageCount":4},controls:controls("dark",4),mediaSlots:[mediaSlot(4)],Component:Signature06ArchitecturalCaseGrid},
{key:"theme14_signature_material_comparison_grid",slot:"signature-material-comparison-grid",label:"External signature · material-comparison-grid",roles:["comparison"],moduleFamily:"comparison",archetypeId:"material-comparison-grid",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.42.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["五个严格矩形单元组成不等宽建筑网格","深浅橄榄、灰白和一张黑白建筑图形成材料样板感","标题位于右上独立单元并以短横线收束"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"特许经营\n设计","lead":"以光环境、家具、服务式办公与垂直绿化比较空间策略。","cards":[{"title":"光污染控制","body":"降低眩光并保持层次。"},{"title":"定制家具","body":"适配多种使用场景。"},{"title":"服务式公寓","body":"把空间服务嵌入运营。"},{"title":"垂直绿化","body":"平衡维护与生态价值。"}],"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature07MaterialComparisonGrid},
{key:"theme14_signature_environment_system_statement",slot:"signature-environment-system-statement",label:"External signature · environment-system-statement",roles:["statement"],moduleFamily:"statement",archetypeId:"environment-system-statement",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-15 16.00.46.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["左上大标题与短横线形成明确观点区","左下两张状态卡、中间说明和右侧竖图构成三列关系","每张状态卡右上保留带白孔圆节点"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"环境图形设计","statement":"商业建筑空间不是四面墙和屋顶，而是为活动精心策划的物理环境。","items":[{"title":"导视系统","body":"融合实用性、品牌识别与情感共鸣。"},{"title":"健康建筑","body":"以功能性和流程效率为基石。"}],"images":[],"imageCount":1},controls:controls("dark",1),mediaSlots:[mediaSlot(1)],Component:Signature08EnvironmentSystemStatement},
{key:"theme14_derived_action_table",slot:"signature-derived-action-table",label:"Style-derived · derived-action-table",roles:["table"],moduleFamily:"table",archetypeId:"derived-action-table",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-02","surface-01","motif-01","color-01"],anchorModuleRefs:["theme14_signature_six_node_program","theme14_signature_material_comparison_grid"],stylePrimitiveRefs:["olive-node","short-rule"],derivationReason:"把模板的分隔线和层级扩展为行动清单；以 theme14_signature_six_node_program、theme14_signature_material_comparison_grid 为视觉锚点。",styleSignals:["标题使用极粗无衬线、紧字距和短行宽，常以两行形成建筑体块感","媒体、数据块和文字沿清晰建筑网格对齐，避免自由漂浮和装饰性重叠","卡片采用小到中等圆角的实色矩形，不使用阴影和半透明玻璃效果","重复使用带白色内孔的橄榄圆节点作为项目、指标和状态符号","深页以墨绿橄榄 #2D3423 作为全画布底色"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"设计行动清单","columns":["阶段","责任","状态"],"rows":[["场地洞察","策略组","完成"],["动线验证","建筑组","进行中"],["材料样板","材料组","待评审"],["运营联调","项目组","待启动"]]},controls:controls("light",0),Component:Derived01ActionTable},
{key:"theme14_derived_closing_call",slot:"signature-derived-closing-call",label:"Style-derived · derived-closing-call",roles:["closing"],moduleFamily:"closing",archetypeId:"derived-closing-call",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-03","surface-02","motif-02","color-02"],anchorModuleRefs:["theme14_signature_split_architecture_cover","theme14_signature_environment_system_statement"],stylePrimitiveRefs:["short-rule","right-angle-arrow"],derivationReason:"用模板的封面语法和签名符号生成收束页；以 theme14_signature_split_architecture_cover、theme14_signature_environment_system_statement 为视觉锚点。",styleSignals:["正文与注释使用克制的中性无衬线，数字百分比采用粗体并与说明分栏","标题下方短横线与圆形节点作为固定定位语法，常出现在左列或卡片角部","深页用米白与苔藓绿卡片形成材料层级，浅页用灰阶块建立体量关系","重复使用短水平规则线和直角方向箭头强调章节与动作","浅页以冷灰白 #ECECEC 作为画布并使用近黑文字"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"让空间回应\n人的真实行为","subtitle":"以严谨秩序连接功能、材料、环境与运营。","action":"进入方案评审"},controls:controls("dark",0),Component:Derived02ClosingCall},
{key:"theme14_derived_composition_breakdown",slot:"signature-derived-composition-breakdown",label:"Style-derived · derived-composition-breakdown",roles:["distribution"],moduleFamily:"distribution",archetypeId:"derived-composition-breakdown",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-01","surface-01","motif-03","color-03"],anchorModuleRefs:["theme14_signature_program_metric_overview","theme14_signature_material_comparison_grid"],stylePrimitiveRefs:["right-angle-arrow","stepped-mass"],derivationReason:"把模板的表面和色阶扩展为构成分析；以 theme14_signature_program_metric_overview、theme14_signature_material_comparison_grid 为视觉锚点。",styleSignals:["标题使用极粗无衬线、紧字距和短行宽，常以两行形成建筑体块感","深浅页面交替出现，均使用严格的矩形分栏与大面积负空间","卡片采用小到中等圆角的实色矩形，不使用阴影和半透明玻璃效果","阶梯高低块、比例数字和严谨四宫格共同模拟建筑体量与空间层级","中层表面使用苔藓绿 #667553 区分指标与材料模块"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"空间构成分析","segments":[{"label":"公共空间","value":38},{"label":"工作空间","value":34},{"label":"服务空间","value":18},{"label":"交通空间","value":10}],"summary":"以公共性和效率共同校准体量分配。"},controls:controls("light",0),Component:Derived03CompositionBreakdown},
{key:"theme14_derived_ecosystem_relationship",slot:"signature-derived-ecosystem-relationship",label:"Style-derived · derived-ecosystem-relationship",roles:["relationship"],moduleFamily:"relationship",archetypeId:"derived-ecosystem-relationship",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-02","surface-02","motif-01","color-04"],anchorModuleRefs:["theme14_signature_stepped_year_blocks","theme14_signature_material_comparison_grid"],stylePrimitiveRefs:["stepped-mass","monochrome-media"],derivationReason:"把模板的网格和节点符号扩展为关系网络；以 theme14_signature_stepped_year_blocks、theme14_signature_material_comparison_grid 为视觉锚点。",styleSignals:["正文与注释使用克制的中性无衬线，数字百分比采用粗体并与说明分栏","媒体、数据块和文字沿清晰建筑网格对齐，避免自由漂浮和装饰性重叠","深页用米白与苔藓绿卡片形成材料层级，浅页用灰阶块建立体量关系","重复使用带白色内孔的橄榄圆节点作为项目、指标和状态符号","高对比文字与结构线使用米白 #F3F3ED 或近黑 #10110E"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"空间系统关系","nodes":[{"id":"site","label":"场地"},{"id":"people","label":"人群"},{"id":"flow","label":"流线"},{"id":"material","label":"材料"},{"id":"operation","label":"运营"}],"links":[["site","flow"],["people","flow"],["flow","material"],["material","operation"]]},controls:controls("dark",0),Component:Derived04EcosystemRelationship},
{key:"theme14_derived_proportion_scorecard",slot:"signature-derived-proportion-scorecard",label:"Style-derived · derived-proportion-scorecard",roles:["proportion"],moduleFamily:"proportion",archetypeId:"derived-proportion-scorecard",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-03","surface-01","motif-02","color-01"],anchorModuleRefs:["theme14_signature_program_metric_overview","theme14_signature_material_comparison_grid"],stylePrimitiveRefs:["monochrome-media","olive-node"],derivationReason:"把模板的指标语法扩展为比例与进度页；以 theme14_signature_program_metric_overview、theme14_signature_material_comparison_grid 为视觉锚点。",styleSignals:["标题使用极粗无衬线、紧字距和短行宽，常以两行形成建筑体块感","标题下方短横线与圆形节点作为固定定位语法，常出现在左列或卡片角部","卡片采用小到中等圆角的实色矩形，不使用阴影和半透明玻璃效果","重复使用短水平规则线和直角方向箭头强调章节与动作","深页以墨绿橄榄 #2D3423 作为全画布底色"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"方案比例校准","values":[64,78,86],"labels":["开放度","采光率","动线效率"]},controls:controls("light",0),Component:Derived05ProportionScorecard},
{key:"theme14_derived_section_transition",slot:"signature-derived-section-transition",label:"Style-derived · derived-section-transition",roles:["transition"],moduleFamily:"transition",archetypeId:"derived-section-transition",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-01","surface-02","motif-03","color-02"],anchorModuleRefs:["theme14_signature_split_architecture_cover","theme14_signature_six_node_program"],stylePrimitiveRefs:["olive-node","short-rule"],derivationReason:"用模板的标题层级和签名符号建立章节过渡；以 theme14_signature_split_architecture_cover、theme14_signature_six_node_program 为视觉锚点。",styleSignals:["正文与注释使用克制的中性无衬线，数字百分比采用粗体并与说明分栏","深浅页面交替出现，均使用严格的矩形分栏与大面积负空间","深页用米白与苔藓绿卡片形成材料层级，浅页用灰阶块建立体量关系","阶梯高低块、比例数字和严谨四宫格共同模拟建筑体量与空间层级","浅页以冷灰白 #ECECEC 作为画布并使用近黑文字"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","kicker":"SECTION / MATERIAL","title":"从空间秩序\n进入材料表达","sectionNumber":"04"},controls:controls("dark",0),Component:Derived06SectionTransition},
{key:"theme14_derived_alternate_cover",slot:"signature-derived-alternate-cover",label:"Style-derived · derived-alternate-cover",roles:["cover"],moduleFamily:"cover",archetypeId:"derived-alternate-cover",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-02","surface-01","motif-01","color-03"],anchorModuleRefs:["theme14_signature_split_architecture_cover","theme14_signature_six_node_program"],stylePrimitiveRefs:["short-rule","right-angle-arrow"],derivationReason:"在不改变 Style DNA 的前提下生成第二种封面构图；以 theme14_signature_split_architecture_cover、theme14_signature_six_node_program 为视觉锚点。",styleSignals:["标题使用极粗无衬线、紧字距和短行宽，常以两行形成建筑体块感","媒体、数据块和文字沿清晰建筑网格对齐，避免自由漂浮和装饰性重叠","卡片采用小到中等圆角的实色矩形，不使用阴影和半透明玻璃效果","重复使用带白色内孔的橄榄圆节点作为项目、指标和状态符号","中层表面使用苔藓绿 #667553 区分指标与材料模块"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"ARCHITECTURE / 2026","title":"空间不是容器\n而是行为的界面","subtitle":"建筑设计与运营整合提案","media":null,"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Derived07AlternateCover},
{key:"theme14_derived_media_case_study",slot:"signature-derived-media-case-study",label:"Style-derived · derived-media-case-study",roles:["media"],moduleFamily:"media",archetypeId:"derived-media-case-study",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-03","media-02","motif-02","color-04"],anchorModuleRefs:["theme14_signature_architectural_case_grid","theme14_signature_split_architecture_cover"],stylePrimitiveRefs:["right-angle-arrow","stepped-mass"],derivationReason:"把模板的图片裁切与图注语法扩展为案例页；以 theme14_signature_architectural_case_grid、theme14_signature_split_architecture_cover 为视觉锚点。",styleSignals:["正文与注释使用克制的中性无衬线，数字百分比采用粗体并与说明分栏","标题下方短横线与圆形节点作为固定定位语法，常出现在左列或卡片角部","图片常占据半页、横向通栏或固定网格单元，不加彩色蒙版和复杂滤镜","重复使用短水平规则线和直角方向箭头强调章节与动作","高对比文字与结构线使用米白 #F3F3ED 或近黑 #10110E"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","title":"城市界面案例","media":null,"caption":"以黑白建筑摄影验证体量、立面与城市关系。","facts":[{"label":"场地","value":"12,800㎡"},{"label":"容积率","value":"4.2"},{"label":"开放空间","value":"38%"},{"label":"周期","value":"28个月"}],"images":[],"imageCount":3},controls:controls("dark",3),mediaSlots:[mediaSlot(3)],Component:Derived08MediaCaseStudy}
];
