export const DINGTALK_SSO_SYSTEM_INTEGRATION_PROVIDER = 'dingtalk-sso'
export const DINGTALK_CONNECTOR_INTEGRATION_PROVIDER = 'dingtalk-connector'
export const DINGTALK_SYSTEM_INTEGRATION_PROVIDERS = [
  DINGTALK_SSO_SYSTEM_INTEGRATION_PROVIDER,
  DINGTALK_CONNECTOR_INTEGRATION_PROVIDER
] as const

export const DINGTALK_CONNECTOR_AUTH_INTEGRATION_URL = `/settings/integration/create?provider=${DINGTALK_CONNECTOR_INTEGRATION_PROVIDER}`
