import React from 'react';

const canvasContract={designWidth:1920,designHeight:1080,rootMode:'fill-parent',backgroundMode:'opaque'};
const controls=(tone,mediaMax=0)=>[
  {key:'tone',label:'画布明暗',type:'select',default:tone,options:[{value:'light',label:'浅色'},{value:'dark',label:'深色'}],effect:{scope:'global',targets:['canvas','surface','typography'],minChangedRatio:.15,minRegions:8}},
  {key:'showOrnament',label:'主题装饰',type:'toggle',default:true,effect:{scope:'component',targets:['ornament'],minChangedRatio:.01,minRegions:1}},
  ...(mediaMax?[{key:'imageCount',label:'图片数量',type:'range',min:0,max:mediaMax,default:mediaMax,effect:{scope:'section',targets:['media','layout'],minChangedRatio:.01,minRegions:2}}]:[])
];
const mediaSlot=max=>({field:'images',presetProp:'props.images',countKey:'imageCount',acceptedKinds:['image'],max,canPresetMedia:true});
const pal=tone=>tone==='dark'?{bg:'#111111',fg:'#F2F1EF',muted:'#BDB9B2',surface:'#292929',line:'#4A4742'}:{bg:'#F2F1EF',fg:'#111111',muted:'#66615A',surface:'#FFFFFF',line:'#C9C4BD'};
function Arrow({color='#111111',size=58}){return <span style={{width:size,height:size,border:'2px solid '+color,borderRadius:'50%',display:'grid',placeItems:'center',fontSize:size*.5,fontWeight:900,color,flex:'0 0 auto'}}>↗</span>}
function Pill({children,color='#F36C2B'}){return <span style={{display:'inline-block',padding:'10px 22px',borderRadius:99,background:color,color:'#111',fontSize:17,fontWeight:850}}>{children}</span>}
function Media({src,color='#856BEA',style}){return <div style={{position:'relative',overflow:'hidden',borderRadius:30,background:'linear-gradient(135deg,'+color+',#F7B0CB 42%,#B7F23A)',...style}}>{src?<img src={typeof src==='string'?src:src.src} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<><i style={{position:'absolute',width:'70%',height:'160%',left:'8%',top:'-30%',borderRadius:'50%',background:'rgba(255,255,255,.3)',transform:'rotate(25deg)'}}/><i style={{position:'absolute',width:'45%',height:'120%',right:'-8%',top:'4%',borderRadius:'50%',background:'rgba(255,255,255,.2)'}}/></>}</div>}
function Header({c,kicker='创新的未来'}){return <div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><b style={{fontSize:17,letterSpacing:'.08em'}}>{kicker}</b><span style={{display:'flex',alignItems:'center',gap:10,color:c.muted}}><i style={{width:22,height:22,borderRadius:'50%',background:'#856BEA',boxShadow:'18px 0 0 #B7F23A'}}/>BRIGHT LOOP</span></div>}
function ThemePage(props){const {variant,family,tone='light',showOrnament=true}=props,c=pal(tone),imageCount=props.imageCount??9,images=(props.images||[]).slice(0,imageCount),media=images[0]||props.media,baseBg=imageCount===0?c.surface:c.bg,canvasBg=showOrnament?'linear-gradient(135deg,'+baseBg+' 0 88%,#B7F23A 88% 94%,#856BEA 94% 100%)':baseBg;const root={width:'100%',height:'100%',position:'relative',overflow:'hidden',boxSizing:'border-box',background:canvasBg,color:c.fg,fontFamily:'Inter, PingFang SC, sans-serif',padding:58};const title={margin:0,fontSize:76,lineHeight:1.02,letterSpacing:'-.055em',whiteSpace:'pre-line',fontWeight:950};const ornament=showOrnament?<div style={{position:'absolute',right:38,bottom:30}}><Arrow color={c.fg} size={52}/></div>:null;
  if(family==='cover'){const alt=variant.includes('alternate');return <section style={root}>{alt?<div style={{height:'100%',display:'grid',gridTemplateColumns:'1fr .85fr',gap:44}}><div style={{display:'flex',flexDirection:'column'}}><Header c={c} kicker={props.kicker}/><h1 style={{...title,fontSize:88,marginTop:'auto'}}>{props.title}</h1><p style={{fontSize:24,color:c.muted}}>{props.subtitle}</p></div><Media src={media} style={{height:'100%'}}/></div>:<div style={{height:'100%',display:'grid',gridTemplateRows:'54% 1fr',gap:38}}><Media src={media} style={{height:'100%'}}/><div style={{display:'grid',gridTemplateColumns:'1fr 300px',alignItems:'end'}}><div><Pill color="#B7F23A">{props.kicker}</Pill><h1 style={{...title,fontSize:78,marginTop:18}}>{props.title}</h1><p style={{fontSize:22,color:c.muted}}>{props.subtitle}</p></div><Header c={c} kicker={props.brand}/></div></div>}{ornament}</section>}
  if(family==='table'){return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:38}}>{props.title}</h1><div style={{display:'flex',gap:12,margin:'24px 0'}}>{(props.pills||[]).map((x,i)=><Pill key={x} color={['#856BEA','#B7F23A','#F36C2B'][i%3]}>{x}</Pill>)}</div><div style={{marginTop:20,borderTop:'1px solid '+c.line}}>{(props.rows||[]).map((r,i)=><div key={i} style={{minHeight:92,display:'grid',gridTemplateColumns:'90px 320px 1fr 56px',alignItems:'center',borderBottom:'1px solid '+c.line}}><b>0{i+1}</b><strong style={{fontSize:25}}>{r.title}</strong><span style={{fontSize:19,color:c.muted}}>{r.body}</span><Arrow color={c.fg} size={38}/></div>)}</div></section>}
  if(family==='metrics'){const metrics=props.metrics||[];return <section style={root}><div style={{display:'grid',gridTemplateColumns:'1.05fr .75fr',height:'100%',gap:42}}><div style={{display:'flex',flexDirection:'column'}}><Header c={c} kicker={props.kicker}/><h1 style={{...title,marginTop:70}}>{props.title}</h1><p style={{fontSize:21,lineHeight:1.55,color:c.muted,maxWidth:700}}>{props.body}</p><div style={{marginTop:'auto',display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:20}}>{metrics.map((m,i)=><article key={i} style={{minHeight:190,borderRadius:28,padding:26,background:['#B7F23A','#F36C2B','#856BEA'][i%3],color:'#111'}}><b style={{fontSize:52}}>{m.value}</b><h3 style={{fontSize:20}}>{m.label}</h3><span>{m.delta||m.note}</span></article>)}</div>{props.trend&&<div style={{height:120,display:'flex',alignItems:'end',gap:18,marginTop:24}}>{props.trend.map((v,i)=><i key={i} style={{width:46,height:v,background:i===props.trend.length-1?'#F36C2B':'#856BEA',borderRadius:'14px 14px 0 0'}}/>)}</div>}</div><Media src={media} style={{height:'100%'}}/></div></section>}
  if(family==='comparison'){return <section style={root}><Header c={c}/><div style={{textAlign:'center',margin:'44px 0 38px'}}><h1 style={{...title,fontSize:68}}>{props.title}</h1><p style={{fontSize:21,color:c.muted}}>{props.lead}</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:28,height:590}}>{(props.cards||[]).map((x,i)=><article key={i} style={{borderRadius:32,padding:38,background:['#F36C2B','#856BEA','#B7F23A'][i%3],color:'#111',display:'flex',flexDirection:'column'}}><b>0{i+1}</b><h2 style={{fontSize:36}}>{x.title}</h2><p style={{fontSize:20,lineHeight:1.55}}>{x.body}</p><div style={{marginTop:'auto',alignSelf:'end'}}><Arrow/></div></article>)}</div></section>}
  if(family==='timeline'){return <section style={root}><div style={{display:'grid',gridTemplateColumns:'620px 1fr',gap:50,height:'100%'}}><div><Header c={c} kicker={props.kicker}/><h1 style={{...title,marginTop:170}}>{props.title}</h1><div style={{marginTop:45}}>{(props.stages||[]).map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'150px 1fr',gap:22,padding:'18px 0',borderBottom:'1px solid '+c.line}}><Pill color={i===2?'#F36C2B':'#B7F23A'}>{x.label}</Pill><div><b style={{fontSize:22}}>{x.title}</b><p style={{margin:'6px 0',color:c.muted}}>{x.body}</p></div></div>)}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}><Media src={images[0]} style={{gridColumn:'1 / 3',height:480}}/><Media src={images[1]} style={{height:360}}/><Media src={images[2]} color="#F36C2B" style={{height:360}}/></div></div></section>}
  if(family==='media'){const items=props.items||props.facts||[];return <section style={root}><Header c={c} kicker={props.kicker}/><div style={{display:'grid',gridTemplateColumns:'500px 1fr',gap:42,height:'calc(100% - 45px)',paddingTop:55}}><div><h1 style={title}>{props.title}</h1><p style={{fontSize:21,lineHeight:1.55,color:c.muted}}>{props.body||props.caption}</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}>{[0,1,2].map((n)=><article key={n} style={{position:'relative',overflow:'hidden',borderRadius:30}}><Media src={images[n]} color={['#B7F23A','#856BEA','#F36C2B'][n]} style={{position:'absolute',inset:0}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(transparent 45%,rgba(0,0,0,.75))'}}/><div style={{position:'absolute',left:24,right:24,bottom:22,color:'#fff'}}><h3 style={{fontSize:26}}>{items[n]?.title||items[n]?.label||'案例 '+(n+1)}</h3><p>{items[n]?.body||items[n]?.value}</p><Pill color="#FFFFFF">查看案例 ↗</Pill></div></article>)}</div></div></section>}
  if(family==='statement'||family==='closing'){return <section style={root}><Header c={c}/><div style={{height:'calc(100% - 40px)',display:'grid',gridTemplateColumns:'1fr .72fr',gap:38,alignItems:'center'}}><div><Pill color="#856BEA">KEY MESSAGE</Pill><h1 style={{...title,fontSize:86,marginTop:28}}>{props.title}</h1><p style={{fontSize:30,lineHeight:1.42,maxWidth:980}}>{props.statement||props.subtitle}</p><Pill color="#B7F23A">{props.action||props.metric?.label||'继续前进'} →</Pill></div>{media?<Media src={media} style={{height:720}}/>:<article style={{height:520,borderRadius:34,padding:44,background:'#B7F23A',color:'#111',display:'flex',flexDirection:'column',justifyContent:'space-between'}}><b style={{fontSize:68}}>{props.metric?.value||'NEXT'}</b><p style={{fontSize:24}}>{props.body||props.subtitle}</p><Arrow size={76}/></article>}</div></section>}
  if(family==='distribution'){return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:54}}>{props.title}</h1><div style={{display:'flex',height:430,marginTop:75,borderRadius:34,overflow:'hidden'}}>{(props.segments||[]).map((s,i)=><article key={i} style={{flex:s.value,background:s.color||['#B7F23A','#856BEA','#F36C2B'][i%3],color:'#111',padding:30,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><b style={{fontSize:54}}>{s.value}%</b><strong style={{fontSize:24}}>{s.label}</strong></article>)}</div><p style={{fontSize:24,color:c.muted}}>{props.summary}</p></section>}
  if(family==='relationship'){return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:45}}>{props.title}</h1><div style={{position:'relative',height:650,marginTop:35}}>{(props.links||[]).map((x,i)=><i key={i} style={{position:'absolute',left:240+i*230,top:250+(i%2)*90,width:280,height:4,background:['#B7F23A','#856BEA','#F36C2B'][i%3],transform:'rotate('+(-18+i*11)+'deg)'}}/>)}{(props.nodes||[]).map((n,i)=><article key={n.id} style={{position:'absolute',left:100+(i%3)*520,top:80+Math.floor(i/3)*330,width:230,height:150,borderRadius:75,background:['#B7F23A','#856BEA','#F36C2B'][i%3],color:'#111',display:'grid',placeItems:'center',fontSize:27,fontWeight:900}}>{n.label}</article>)}</div></section>}
  if(family==='proportion'){return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:60}}>{props.title}</h1><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:34,marginTop:90}}>{(props.values||[]).map((v,i)=><article key={i} style={{borderRadius:34,background:['#B7F23A','#856BEA','#F36C2B'][i%3],color:'#111',padding:36,height:430}}><b style={{fontSize:78}}>{v}%</b><div style={{height:180,border:'18px solid rgba(17,17,17,.16)',borderTopColor:'#111',borderRadius:'50%',margin:'30px auto',width:180}}/><h3 style={{fontSize:26}}>{props.labels?.[i]}</h3></article>)}</div></section>}
  if(family==='ranking'){return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:50}}>{props.title}</h1><div style={{marginTop:65}}>{(props.items||[]).map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'90px 1fr 220px',alignItems:'center',height:120,borderBottom:'1px solid '+c.line,background:x.name===props.highlight?'#B7F23A':'transparent',color:x.name===props.highlight?'#111':c.fg,padding:'0 24px',borderRadius:x.name===props.highlight?24:0}}><b>0{i+1}</b><h2>{x.name}</h2><strong style={{fontSize:46}}>{x.value}</strong></div>)}</div></section>}
  if(family==='transition'){return <section style={{...root,background:tone==='dark'?(showOrnament?'linear-gradient(135deg,#856BEA 0 82%,#B7F23A 82%)':'#856BEA'):(showOrnament?'linear-gradient(135deg,#B7F23A 0 82%,#F36C2B 82%)':'#B7F23A'),color:'#111'}}><Pill color="#B7F23A">{props.kicker}</Pill><div style={{height:'80%',display:'grid',gridTemplateColumns:'1fr 360px',alignItems:'center'}}><h1 style={{...title,fontSize:110}}>{props.title}</h1><b style={{fontSize:240,lineHeight:1,textAlign:'right'}}>{props.sectionNumber}</b></div><div style={{position:'absolute',left:58,right:58,bottom:55,height:4,background:'#111'}}/></section>}
  return <section style={root}><Header c={c}/><h1 style={{...title,marginTop:80}}>{props.title}</h1><p style={{fontSize:24,color:c.muted,maxWidth:760}}>{props.body}</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:28,marginTop:80}}>{(props.items||[]).map((x,i)=><article key={i} style={{padding:34,borderTop:'1px solid '+c.line}}><Pill>{x.label}</Pill><h2 style={{fontSize:34}}>{x.title}</h2><p style={{fontSize:20,color:c.muted}}>{x.body}</p></article>)}</div>{ornament}</section>
}
function Signature01RoundedMediaCover(props){return <ThemePage variant="rounded-media-cover" family="cover" {...props}/>}
function Signature02PillAgendaTable(props){return <ThemePage variant="pill-agenda-table" family="table" {...props}/>}
function Signature03EditorialMetricImage(props){return <ThemePage variant="editorial-metric-image" family="metrics" {...props}/>}
function Signature04ThreeColorStrategy(props){return <ThemePage variant="three-color-strategy" family="comparison" {...props}/>}
function Signature05MosaicActionPath(props){return <ThemePage variant="mosaic-action-path" family="timeline" {...props}/>}
function Signature06DualTrackNarrative(props){return <ThemePage variant="dual-track-narrative" family="general" {...props}/>}
function Signature07TriptychActionMedia(props){return <ThemePage variant="triptych-action-media" family="media" {...props}/>}
function Signature08QuoteMetricShowcase(props){return <ThemePage variant="quote-metric-showcase" family="statement" {...props}/>}
function Derived01ClosingCall(props){return <ThemePage variant="derived-closing-call" family="closing" {...props}/>}
function Derived02CompositionBreakdown(props){return <ThemePage variant="derived-composition-breakdown" family="distribution" {...props}/>}
function Derived03EcosystemRelationship(props){return <ThemePage variant="derived-ecosystem-relationship" family="relationship" {...props}/>}
function Derived04ProportionScorecard(props){return <ThemePage variant="derived-proportion-scorecard" family="proportion" {...props}/>}
function Derived05RankedSignals(props){return <ThemePage variant="derived-ranked-signals" family="ranking" {...props}/>}
function Derived06SectionTransition(props){return <ThemePage variant="derived-section-transition" family="transition" {...props}/>}
function Derived07AlternateCover(props){return <ThemePage variant="derived-alternate-cover" family="cover" {...props}/>}
function Derived08MetricDashboard(props){return <ThemePage variant="derived-metric-dashboard" family="metrics" {...props}/>}
export const signaturePages=[
{key:"theme13_signature_rounded_media_cover",slot:"signature-rounded-media-cover",label:"External signature · rounded-media-cover",roles:["cover"],moduleFamily:"cover",archetypeId:"rounded-media-cover",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.05.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["上方宽幅圆角媒体与左下超大标题形成垂直张力","品牌双圆与圆形箭头分别压住两侧底边","标题控制在两行并保留大面积空白"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"CIRCULAR BUSINESS / 2026","title":"循环经济理念\n推动商业变革","subtitle":"从价值重构到规模增长，建立面向未来的商业路径","brand":"创新的未来","images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature01RoundedMediaCover},
{key:"theme13_signature_pill_agenda_table",slot:"signature-pill-agenda-table",label:"External signature · pill-agenda-table",roles:["table"],moduleFamily:"table",archetypeId:"pill-agenda-table",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.14.png","截屏2026-07-17 13.36.48.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["通栏细线划分五个可扫描行","彩色胶囊承担分类或状态而非背景装饰","灰色波浪线在标题区弱化出现且不覆盖文本"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"目录.","pills":["市场介绍","循环经济","规模展示","核心趋势","行动计划"],"rows":[{"title":"复合增长速度","body":"公司侧增长与核心价值观"},{"title":"战略技术趋势","body":"全球竞争与技术分化"},{"title":"智能体 AI","body":"自主行动的工作流重组"},{"title":"专用芯片","body":"计算需求与供给结构"},{"title":"顶尖创新","body":"可持续工业进程"}]},controls:controls("light",0),Component:Signature02PillAgendaTable},
{key:"theme13_signature_editorial_metric_image",slot:"signature-editorial-metric-image",label:"External signature · editorial-metric-image",roles:["metrics"],moduleFamily:"metrics",archetypeId:"editorial-metric-image",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.18.png","截屏2026-07-17 13.36.39.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["右侧竖向圆角图片作为稳定视觉锚点","青柠与橙色指标卡以局部叠压建立层级","左侧标题正文保持窄列和高留白"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"引言","title":"复合式创新力量\n正在发挥作用","body":"增长来自技术、资源与组织方式的同步变化。用清晰指标判断机会，并把判断落实为可执行动作。","metrics":[{"value":"15%","label":"年度复合增长","note":"新业务在核心组合中的贡献持续提升"},{"value":"85%","label":"协同完成率","note":"关键团队进入稳定交付节奏"}],"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature03EditorialMetricImage},
{key:"theme13_signature_three_color_strategy",slot:"signature-three-color-strategy",label:"External signature · three-color-strategy",roles:["comparison"],moduleFamily:"comparison",archetypeId:"three-color-strategy",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.22.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["橙紫青柠三张等宽大卡横向并列","白色圆形动作切口贴近卡片右下角","卡内文字层级一致且不使用阴影"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"战略科技趋势","lead":"以全球竞争、技术分化和伦理使命组织判断。","cards":[{"title":"全球竞争","body":"建立跨区域持续响应能力。"},{"title":"技术分化","body":"把关键路径拆解为阶段目标。"},{"title":"伦理使命","body":"让效率与长期价值同时进入决策。"}]},controls:controls("light",0),Component:Signature04ThreeColorStrategy},
{key:"theme13_signature_mosaic_action_path",slot:"signature-mosaic-action-path",label:"External signature · mosaic-action-path",roles:["timeline"],moduleFamily:"timeline",archetypeId:"mosaic-action-path",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.27.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["左侧用胶囊标题和分隔行组织阶段动作","右侧由三块不等比圆角媒体拼贴形成路径感","橙色角块作为页级定位标记"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"行动路径","title":"人机协同\n自适应自主化","stages":[{"label":"基础","title":"建立信任","body":"明确边界与责任。"},{"label":"协同","title":"连接流程","body":"让数据和决策稳定流动。"},{"label":"规模","title":"复制能力","body":"把验证沉淀为组织能力。"}],"images":[],"imageCount":3},controls:controls("light",3),mediaSlots:[mediaSlot(3)],Component:Signature05MosaicActionPath},
{key:"theme13_signature_dual_track_narrative",slot:"signature-dual-track-narrative",label:"External signature · dual-track-narrative",roles:["general"],moduleFamily:"general",archetypeId:"dual-track-narrative",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.31.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["大标题与正文占据左半区","右侧两条叙事轨道以橙色胶囊开头","极大留白和角块维持编辑式节奏"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"整合战略\n扩大创新边界","body":"用两条并行叙事解释增长来自哪里、如何形成长期优势。","items":[{"label":"01 / 市场","title":"需求牵引","body":"抓住高价值场景并持续验证。"},{"label":"02 / 组织","title":"能力供给","body":"让人才、流程和技术共同演进。"}]},controls:controls("light",0),Component:Signature06DualTrackNarrative},
{key:"theme13_signature_triptych_action_media",slot:"signature-triptych-action-media",label:"External signature · triptych-action-media",roles:["media"],moduleFamily:"media",archetypeId:"triptych-action-media",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.34.png","截屏2026-07-17 13.36.42.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["三张高纵横比圆角媒体并列或组成二加一结构","媒体底部渐变承载白色标题与简述","动作胶囊含圆形箭头并贴近卡片底边"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"智能体系统","title":"多步骤行动系统","body":"把复杂工作拆成自主行动、协同传递与投资判断。","items":[{"title":"自主行动","body":"围绕目标自动规划并反馈。"},{"title":"流程传递","body":"让人机协作在边界中流动。"},{"title":"投资判断","body":"用证据校准投入节奏。"}],"images":[],"imageCount":3},controls:controls("light",3),mediaSlots:[mediaSlot(3)],Component:Signature07TriptychActionMedia},
{key:"theme13_signature_quote_metric_showcase",slot:"signature-quote-metric-showcase",label:"External signature · quote-metric-showcase",roles:["statement"],moduleFamily:"statement",archetypeId:"quote-metric-showcase",moduleStrategy:"new",evidenceMode:"observed",evidenceRefs:["截屏2026-07-17 13.36.39.png","截屏2026-07-17 13.36.42.png"],derivedFromRules:[],anchorModuleRefs:[],stylePrimitiveRefs:[],derivationReason:null,styleSignals:["一句观点与超大数字分别落在亮色卡片中","卡片与竖向媒体组成强弱分明的三列结构","黑色正文与彩色表面保持高对比"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"重新定义增长","statement":"“真正的循环，不是回到起点，而是让每一轮价值更高。”","metric":{"value":"+500K","label":"年度新增用户"},"body":"亮色观点卡与指标卡共同构成可记忆的结论。","images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Signature08QuoteMetricShowcase},
{key:"theme13_derived_closing_call",slot:"signature-derived-closing-call",label:"Style-derived · derived-closing-call",roles:["closing"],moduleFamily:"closing",archetypeId:"derived-closing-call",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-02","surface-01","motif-01","color-01"],anchorModuleRefs:["theme13_signature_rounded_media_cover","theme13_signature_quote_metric_showcase"],stylePrimitiveRefs:["orbit-arrow","rounded-color-card"],derivationReason:"用模板的封面语法和签名符号生成收束页；以 theme13_signature_rounded_media_cover、theme13_signature_quote_metric_showcase 为视觉锚点。",styleSignals:["标题使用极粗无衬线并采用明显大于正文的编辑式尺度，允许两行紧凑断行","内容常沿左侧标题区与右侧媒体或卡片区分栏，元素允许有控制的跨区叠压","核心信息使用 28 到 40 像素大圆角实体卡，几乎不使用阴影","重复使用圆形箭头、轨道圆环和相邻双圆构成循环与行动符号","以暖灰白 #F2F1EF 作为大面积画布，保持编辑式留白"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"让下一轮增长\n从现在开始","subtitle":"把循环思维转化为清晰、可执行、可衡量的商业行动。","action":"启动共创"},controls:controls("light",0),Component:Derived01ClosingCall},
{key:"theme13_derived_composition_breakdown",slot:"signature-derived-composition-breakdown",label:"Style-derived · derived-composition-breakdown",roles:["distribution"],moduleFamily:"distribution",archetypeId:"derived-composition-breakdown",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-03","surface-02","motif-02","color-02"],anchorModuleRefs:["theme13_signature_editorial_metric_image","theme13_signature_three_color_strategy"],stylePrimitiveRefs:["rounded-color-card","pill-label"],derivationReason:"把模板的表面和色阶扩展为构成分析；以 theme13_signature_editorial_metric_image、theme13_signature_three_color_strategy 为视觉锚点。",styleSignals:["正文保持中小号中性无衬线，数字与百分比使用重字重形成信息锚点","目录和表格使用通栏细线建立秩序，同时用胶囊标签打破严肃感","媒体容器采用大圆角裁切，卡片可用白色圆形切口或悬浮圆钮形成动作感","使用灰色手绘波浪线、彩色角块和小型品牌圆标作为跨页识别元素","以近黑 #111111 承担超大标题、表格线和关键正文"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"价值构成分析","segments":[{"label":"产品价值","value":42,"color":"#B7F23A"},{"label":"服务价值","value":33,"color":"#856BEA"},{"label":"生态价值","value":25,"color":"#F36C2B"}],"summary":"三类价值共同形成可持续增长飞轮。"},controls:controls("light",0),Component:Derived02CompositionBreakdown},
{key:"theme13_derived_ecosystem_relationship",slot:"signature-derived-ecosystem-relationship",label:"Style-derived · derived-ecosystem-relationship",roles:["relationship"],moduleFamily:"relationship",archetypeId:"derived-ecosystem-relationship",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-01","surface-01","motif-03","color-03"],anchorModuleRefs:["theme13_signature_mosaic_action_path","theme13_signature_three_color_strategy"],stylePrimitiveRefs:["pill-label","corner-block"],derivationReason:"把模板的网格和节点符号扩展为关系网络；以 theme13_signature_mosaic_action_path、theme13_signature_three_color_strategy 为视觉锚点。",styleSignals:["标题使用极粗无衬线并采用明显大于正文的编辑式尺度，允许两行紧凑断行","页面以不对称编辑网格组织，大标题、大片留白和一组高饱和卡片形成张力","核心信息使用 28 到 40 像素大圆角实体卡，几乎不使用阴影","胶囊标签既用于章节分类也用于表格状态，颜色取自青柠、紫、橙三色","以荧光青柠 #B7F23A 作为增长与行动强调色"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"增长生态关系","nodes":[{"id":"customer","label":"客户"},{"id":"product","label":"产品"},{"id":"partner","label":"伙伴"},{"id":"data","label":"数据"},{"id":"brand","label":"品牌"}],"links":[["customer","product"],["product","data"],["data","partner"],["partner","brand"]]},controls:controls("light",0),Component:Derived03EcosystemRelationship},
{key:"theme13_derived_proportion_scorecard",slot:"signature-derived-proportion-scorecard",label:"Style-derived · derived-proportion-scorecard",roles:["proportion"],moduleFamily:"proportion",archetypeId:"derived-proportion-scorecard",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-02","surface-02","motif-01","color-04"],anchorModuleRefs:["theme13_signature_editorial_metric_image","theme13_signature_three_color_strategy"],stylePrimitiveRefs:["corner-block","squiggle-rail"],derivationReason:"把模板的指标语法扩展为比例与进度页；以 theme13_signature_editorial_metric_image、theme13_signature_three_color_strategy 为视觉锚点。",styleSignals:["正文保持中小号中性无衬线，数字与百分比使用重字重形成信息锚点","内容常沿左侧标题区与右侧媒体或卡片区分栏，元素允许有控制的跨区叠压","媒体容器采用大圆角裁切，卡片可用白色圆形切口或悬浮圆钮形成动作感","重复使用圆形箭头、轨道圆环和相邻双圆构成循环与行动符号","以明亮紫 #856BEA 和橙色 #F36C2B 形成三色卡片系统"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"关键比例记分卡","values":[72,58,86],"labels":["市场验证","产品采用","伙伴协同"]},controls:controls("light",0),Component:Derived04ProportionScorecard},
{key:"theme13_derived_ranked_signals",slot:"signature-derived-ranked-signals",label:"Style-derived · derived-ranked-signals",roles:["ranking"],moduleFamily:"ranking",archetypeId:"derived-ranked-signals",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-03","surface-01","motif-02","color-01"],anchorModuleRefs:["theme13_signature_editorial_metric_image","theme13_signature_pill_agenda_table"],stylePrimitiveRefs:["squiggle-rail","orbit-arrow"],derivationReason:"把模板的数字层级和分隔规则扩展为排行页；以 theme13_signature_editorial_metric_image、theme13_signature_pill_agenda_table 为视觉锚点。",styleSignals:["标题使用极粗无衬线并采用明显大于正文的编辑式尺度，允许两行紧凑断行","目录和表格使用通栏细线建立秩序，同时用胶囊标签打破严肃感","核心信息使用 28 到 40 像素大圆角实体卡，几乎不使用阴影","使用灰色手绘波浪线、彩色角块和小型品牌圆标作为跨页识别元素","以暖灰白 #F2F1EF 作为大面积画布，保持编辑式留白"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"优先信号排行","items":[{"name":"客户留存","value":"92"},{"name":"单位经济性","value":"86"},{"name":"交付效率","value":"79"},{"name":"伙伴覆盖","value":"68"}],"highlight":"客户留存"},controls:controls("light",0),Component:Derived05RankedSignals},
{key:"theme13_derived_section_transition",slot:"signature-derived-section-transition",label:"Style-derived · derived-section-transition",roles:["transition"],moduleFamily:"transition",archetypeId:"derived-section-transition",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-01","surface-02","motif-03","color-02"],anchorModuleRefs:["theme13_signature_rounded_media_cover","theme13_signature_dual_track_narrative"],stylePrimitiveRefs:["orbit-arrow","rounded-color-card"],derivationReason:"用模板的标题层级和签名符号建立章节过渡；以 theme13_signature_rounded_media_cover、theme13_signature_dual_track_narrative 为视觉锚点。",styleSignals:["正文保持中小号中性无衬线，数字与百分比使用重字重形成信息锚点","页面以不对称编辑网格组织，大标题、大片留白和一组高饱和卡片形成张力","媒体容器采用大圆角裁切，卡片可用白色圆形切口或悬浮圆钮形成动作感","胶囊标签既用于章节分类也用于表格状态，颜色取自青柠、紫、橙三色","以近黑 #111111 承担超大标题、表格线和关键正文"],sourceContract:null,canvasContract,defaultProps:{"tone":"dark","kicker":"SECTION / STRATEGY","title":"从洞察进入行动","sectionNumber":"03"},controls:controls("dark",0),Component:Derived06SectionTransition},
{key:"theme13_derived_alternate_cover",slot:"signature-derived-alternate-cover",label:"Style-derived · derived-alternate-cover",roles:["cover"],moduleFamily:"cover",archetypeId:"derived-alternate-cover",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-01","composition-02","surface-01","motif-01","color-03"],anchorModuleRefs:["theme13_signature_rounded_media_cover","theme13_signature_dual_track_narrative"],stylePrimitiveRefs:["rounded-color-card","pill-label"],derivationReason:"在不改变 Style DNA 的前提下生成第二种封面构图；以 theme13_signature_rounded_media_cover、theme13_signature_dual_track_narrative 为视觉锚点。",styleSignals:["标题使用极粗无衬线并采用明显大于正文的编辑式尺度，允许两行紧凑断行","内容常沿左侧标题区与右侧媒体或卡片区分栏，元素允许有控制的跨区叠压","核心信息使用 28 到 40 像素大圆角实体卡，几乎不使用阴影","重复使用圆形箭头、轨道圆环和相邻双圆构成循环与行动符号","以荧光青柠 #B7F23A 作为增长与行动强调色"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","kicker":"BUSINESS PLAN / 2026","title":"增长发生在\n价值重新连接之处","subtitle":"面向投资人与管理团队的商业计划","media":null,"images":[],"imageCount":1},controls:controls("light",1),mediaSlots:[mediaSlot(1)],Component:Derived07AlternateCover},
{key:"theme13_derived_metric_dashboard",slot:"signature-derived-metric-dashboard",label:"Style-derived · derived-metric-dashboard",roles:["metrics"],moduleFamily:"metrics",archetypeId:"derived-metric-dashboard",moduleStrategy:"new",evidenceMode:"inferred",evidenceRefs:[],derivedFromRules:["typography-02","composition-03","surface-02","motif-02","color-04"],anchorModuleRefs:["theme13_signature_editorial_metric_image","theme13_signature_dual_track_narrative"],stylePrimitiveRefs:["pill-label","corner-block"],derivationReason:"把模板的数字、表面和图表语法扩展为指标总览；以 theme13_signature_editorial_metric_image、theme13_signature_dual_track_narrative 为视觉锚点。",styleSignals:["正文保持中小号中性无衬线，数字与百分比使用重字重形成信息锚点","目录和表格使用通栏细线建立秩序，同时用胶囊标签打破严肃感","媒体容器采用大圆角裁切，卡片可用白色圆形切口或悬浮圆钮形成动作感","使用灰色手绘波浪线、彩色角块和小型品牌圆标作为跨页识别元素","以明亮紫 #856BEA 和橙色 #F36C2B 形成三色卡片系统"],sourceContract:null,canvasContract,defaultProps:{"tone":"light","title":"增长仪表盘","metrics":[{"label":"收入增长","value":"+32%","delta":"↑ 8.4%"},{"label":"活跃客户","value":"18.6K","delta":"↑ 12.1%"},{"label":"续约率","value":"91%","delta":"↑ 3.2%"},{"label":"伙伴效率","value":"4.8×","delta":"↑ 0.6×"}],"trend":[28,36,42,55,63,76]},controls:controls("light",0),Component:Derived08MetricDashboard}
];
