jest.mock('@xpert-ai/plugin-sdk', () => ({
  pluginArtifactTableName: (namespace: string, tableKey: string) => `plugin_${namespace}_${tableKey}`
}))

import { XPERT_QUOTATION_TOOL_NAMES } from './constants.js'
import { buildAiReviewPrompt } from './ai-review-prompt.js'

describe('Xpert Quotation AI review prompt', () => {
  it('searches connected knowledgebases with project specifications before web fallback', () => {
    const prompt = buildAiReviewPrompt('quotation-id')
    for (const toolName of XPERT_QUOTATION_TOOL_NAMES) expect(prompt).toContain(toolName)
    expect(prompt).toContain('xpert_quotation_get_current_workbench_context')
    expect(prompt).toContain('不要先要求用户提供 quotationId')
    expect(prompt).toContain('不返回工作表单元格或文件正文')
    expect(prompt).toContain('parsed_file_table_query')
    expect(prompt).toContain('sandbox_read_file')
    expect(prompt.indexOf('xpert_quotation_inspect_workbook')).toBeLessThan(prompt.indexOf('xpert_quotation_start_matching'))
    expect(prompt.indexOf('xpert_quotation_search_quota_components')).toBeLessThan(prompt.indexOf('xpert_quotation_search_knowledge_prices'))
    expect(prompt).toContain('无知识库或无可靠候选时调用 web_search')
    expect(prompt).toContain('完整项目特征/规格')
    expect(prompt).toContain('xpert_quotation_propose_quota_breakdown')
    expect(prompt).toContain('xpert_quotation_recommend_web_quota_breakdown')
    expect(prompt).toContain('uncoveredWorkScopes')
    expect(prompt).toContain('恰好分区')
    expect(prompt).toContain('xpert_quotation_search_resource_prices')
    expect(prompt).toContain('xpert_quotation_recommend_web_resource_price')
    expect(prompt).toContain('resourcePricing.resources')
    expect(prompt).toContain('只有原始 kind=material 的材料暂估/材料表行')
    expect(prompt).toContain('工作表 kind 只是表级初始分类')
    expect(prompt).toContain('directMaterial=true')
    expect(prompt).toContain('真实 URL、标题、逐字摘录')
    expect(prompt).toContain('consumptionPending=true')
    expect(prompt).toContain('不得编造密度、损耗、包装、覆盖率或工日小时口径')
    expect(prompt).toContain('不得使用清单 m2/m3 作为人工、材料或机械资源价格单位')
    expect(prompt).toContain('不得调用 xpert_quotation_review_quota_breakdown、xpert_quotation_review_resource_price 或 xpert_quotation_calculate_comprehensive_rate')
    expect(prompt).toContain('严禁调用 xpert_quotation_review_quota_breakdown')
    expect(prompt).toContain('aiRecommendedKnowledgeCandidateId')
    expect(prompt).toContain('aiKnowledgeEvidence')
    expect(prompt).toContain('自动识别任务严禁调用')
    expect(prompt).toContain('xpert_quotation_apply_patch')
    expect(prompt).toContain('mode=resource_price')
    expect(prompt).toContain('mode=resource_consumption')
    expect(prompt).toContain('Workbench 刷新后显示在对应按钮下方')
    expect(prompt).toContain('最多保留 5 个候选')
    expect(prompt).toContain('两个 follower Agent')
    expect(prompt).not.toContain('priceBookId')
    expect(prompt).not.toContain('价格清单 ID')
  })
})
