export function buildAiReviewPrompt(quotationId: string) {
  return [
    `执行 Xpert Quotation 的 AI 识别、逐行消耗量拆分、资源价格检索与材料价格推荐流程。quotationId=${quotationId}。`,
    '严格按 Agent 职责调用工具：主协调 Agent 只负责工作簿识别、匹配、问题分页和任务分派；逐行 Worker 不连接知识库或 WebTools，只负责一行任务编排、调用两个 follower Agent，并通过 xpert_quotation_propose_quota_breakdown 或 xpert_quotation_recommend_web_quota_breakdown 保存定额提案；消耗量检索 Agent 优先调用 xpert_quotation_search_quota_components，只连接消耗量定额库，并在无知识库或无可靠候选时调用 web_search、web_fetch 返回带 URL 和原文摘录的联网拆解证据；价格检索 Agent 调用资源/材料价格工具，并在无价格知识库或无可靠候选时调用 web_search、web_fetch 和相应联网推荐工具。价格检索 Agent 严禁执行消耗量定额检索，消耗量检索 Agent 严禁执行价格检索。自动识别任务严禁调用 xpert_quotation_review_quota_breakdown、xpert_quotation_review_resource_price、xpert_quotation_calculate_comprehensive_rate 或 xpert_quotation_apply_patch；AI 推荐不是用户审批。',
    '当前工具名称包括：xpert_quotation_get_current_workbench_context、xpert_quotation_get_summary、xpert_quotation_inspect_workbook、xpert_quotation_start_matching、xpert_quotation_list_issues、xpert_quotation_search_quota_components、xpert_quotation_propose_quota_breakdown、xpert_quotation_recommend_web_quota_breakdown、xpert_quotation_review_quota_breakdown、xpert_quotation_search_resource_prices、xpert_quotation_recommend_resource_price、xpert_quotation_recommend_web_resource_price、xpert_quotation_review_resource_price、xpert_quotation_calculate_comprehensive_rate、xpert_quotation_search_knowledge_prices、xpert_quotation_recommend_knowledge_price、xpert_quotation_mark_knowledge_no_match、xpert_quotation_recommend_web_price，以及 web_search、web_fetch。只调用当前 Agent 工具边界中实际存在的名称。',
    '当用户询问当前报价、当前 Workbench 页面、打开的文件、工作表内容或项目数量时，必须先调用 xpert_quotation_get_current_workbench_context。不要先要求用户提供 quotationId；只有工具返回 workbench_context_unavailable 时，才提示用户打开报价 Workbench 或导入文件。该上下文工具只返回项目、视图、文件名、文件路径、版本和状态元数据，不返回工作表单元格或文件正文；需要内容时，使用返回的 filePath 配合 parsed_file_list、parsed_file_search、parsed_file_read、parsed_file_table_query 或 sandbox_read_file 按需读取，XLSX 结构识别仍必须调用 xpert_quotation_inspect_workbook。',
    '步骤 1：必须先调用 xpert_quotation_inspect_workbook。工作表名称、编号、表头行、数据范围和列位置都不固定；只能依据返回的精确工作表名称、单元格地址和值识别分部分项、材料暂估和措施项目表。',
    '步骤 2：严格遵守 inspect_workbook 返回的 mappingContract，为每张相关表生成 sheetMappings。kind=bill 或 material 时 columns.name、quantity、unitPrice、amount 均必填，unitPrice 与 amount 必须是两个不同的空白目标列；只有 kind=measure 且仅有一个价格列时才可省略 amount。必须把“项目特征描述”、材料规格、型号、材质等实际列全部映射到 columns.specification；规格可跨多列。只有 observedTotalLabels 中存在明确小计/合计证据时才映射 totals，否则省略 totals；每个小计 startRow..endRow 必须在数据行内且 targetRow 在自身区间外，尾随小计通常 endRow=targetRow-1。随后调用 xpert_quotation_start_matching，无需任何外部价格文件参数。',
    'Workbench 的单资源按钮会发送一个定向 JSON：mode=resource_price 或 mode=resource_consumption，并带 quotationId、lineId 和一个完整 resource 对象。收到这种消息时，主 Agent 只把同一行和同一资源转交逐行 Worker；不得重新识别整个工作簿、处理其他行、直接检索知识库或把结果只写在聊天中。价格按钮必须由 Worker 转交价格检索 Agent，消耗量按钮必须由 Worker 转交消耗量检索 Agent；子 Agent 返回后必须把候选持久化到该行，Workbench 刷新后显示在对应按钮下方。定向检索不计算综合单价、不审批、不写 Excel。',
    '步骤 3：分页调用 xpert_quotation_list_issues，直到 hasNext=false。对每个未解决的 kind=bill 或 kind=material 行，将 quotationId、lineId、kind、lineNumber、billCode、billName、specification、unit、quantity、discipline 逐字复制到逐行 Worker，一次只处理一行；最多并发两个 Worker。不要把主 Agent 未连接知识库误判为整个流程不可用；检索必须通过已连接知识库的两个 follower Agent 完成。',
    '步骤 4：逐行 Worker 对每一条 kind=bill 行都把同一条 JSON 交给消耗量检索 Agent，并等待返回；Worker 自己没有知识库或 WebTools，严禁直接检索。工作表 kind 只是表级初始分类，不等于行级计价类型。消耗量 Agent 先调用 xpert_quotation_search_quota_components：材料采购/供应/购置且没有施工动作时返回 directMaterial=true；施工清单则检索消耗量定额库。若没有连接消耗量知识库或当前搜索无可靠候选，消耗量 Agent 必须用 web_search/web_fetch 检索工程做法、定额组成和人材机消耗证据，并返回真实 URL、标题、逐字摘录、工作范围、定额名称/单位和资源。Worker 对知识库候选调用 xpert_quotation_propose_quota_breakdown；对联网结果调用 xpert_quotation_recommend_web_quota_breakdown。联网原文没有明确消耗量的资源必须 consumptionPending=true 且 consumption=0，严禁猜数。两类工具都只保存 proposed 提案并返回 resourcePricing.resources，不自动审核、计价或写入；coveredWorkScopes 与 uncoveredWorkScopes 必须对原始 workScopes 恰好分区。',
    '步骤 5：定额或直接材料提案成功后，Worker 逐个把返回的 resourceId 发送给价格检索 Agent，不能自己查价。价格 Agent 先针对人工、机械、材料资源调用 xpert_quotation_search_resource_prices；最多保留 5 个候选。存在可靠结构化候选时调用 xpert_quotation_recommend_resource_price。没有连接价格知识库、搜索不可用或无可靠候选时，调用 web_search/web_fetch 搜索同名同规格同单位的市场/造价信息价，再调用 xpert_quotation_recommend_web_resource_price 保存真实 URL、标题和逐字包含价格及单位的摘录。直接材料 bill 行也走这个资源价格流程。保留 sourceWorkdayHours；只有来源明确给出 quotaWorkdayHours 时才提交。不得使用清单 m2/m3 作为人工、材料或机械资源价格单位，不得编造密度、损耗、包装、覆盖率或工日小时口径。',
    '步骤 6：消耗量拆分和资源价格都只是 proposed/recommended 状态。自动识别阶段不得调用审核、计算或写入工具；也就是不得调用 xpert_quotation_review_quota_breakdown、xpert_quotation_review_resource_price 或 xpert_quotation_calculate_comprehensive_rate。资源候选必须保留给审核页按人工、机械、材料分类展示。未识别消耗量、缺少价格或未覆盖工作仅作为计算警告和人工选择提示，不再生成“计价公式”或“计价阻塞”审核区块。',
    '步骤 7：只有原始 kind=material 的材料暂估/材料表行才由价格检索 Agent 调用 xpert_quotation_search_knowledge_prices，按材料名称、完整项目特征/规格、单位和编码比较最多 5 个候选；匹配时调用 xpert_quotation_recommend_knowledge_price，evidenceQuote 必须逐字包含价格和单位；全部不匹配时逐个调用 xpert_quotation_mark_knowledge_no_match，成功后才允许 web_search/web_fetch 和 xpert_quotation_recommend_web_price。语义为直接材料采购但位于分部分项表的 bill 行，不走此材料行专用工具，而走步骤 5 的材料资源价格流程；不得把材料单价直接绕过资源审核当作施工工程综合单价。',
    '步骤 8：全部处理后再次分页调用 xpert_quotation_list_issues。每个未解决 bill 行都必须含 quotaSearchedAt、quotaBreakdown、quotaPricingResources 和 quotaResourcePrices；每个已检索资源都必须持久化最新候选或 no_match 状态。知识库材料推荐行必须含 aiRecommendedKnowledgeCandidateId、aiRecommendedUnitPrice、aiKnowledgeEvidence，联网推荐行必须含 aiRecommendedUnitPrice、aiRecommendedSourceUnit、aiSources。审核报告只汇总消耗量组成、人材机资源候选、价格候选和计算警告，不输出计价公式或计价阻塞章节。',
    '不得编造知识片段、候选 ID、来源、价格、单位或单元格地址。最终只汇总已持久化的知识库推荐、已持久化的联网推荐，以及需要人工填写或仍缺乏可靠证据的项目，等待用户在审核区一键应用或人工处理。'
  ].join('\n')
}
