import { Injectable } from '@nestjs/common'
import { tool } from '@langchain/core/tools'
import { TAgentMiddlewareMeta } from '@xpert-ai/contracts'
import {
  AgentMiddleware,
  AgentMiddlewareStrategy,
  IAgentMiddlewareContext,
  IAgentMiddlewareStrategy,
  PromiseOrValue
} from '@xpert-ai/plugin-sdk'
import { z } from 'zod/v3'
import {
  TEST_CASE_GENERATE_TOOL_NAME,
  TEST_CASE_GENERATOR_FEATURE,
  TEST_CASE_GENERATOR_ICON,
  TEST_CASE_GENERATOR_MIDDLEWARE_NAME,
  TEST_CASE_DELETE_TOOL_NAME,
  TEST_CASE_LIST_TOOL_NAME,
  TEST_CASE_SAVE_TOOL_NAME
} from './constants'
import { TestCaseGeneratorService } from './test-case-generator.service'
import type { TestCaseSaveProjectInput, TestCaseScope } from './types'
import { TEST_CASE_REQUIREMENT_MIN_LENGTH, validateGeneratedTestCase } from './types'

const testCaseItemSchema = z.object({
  name: z.string().min(1).describe('Test case name, concise and descriptive.'),
  precondition: z.string().describe('Precondition or setup state before executing the steps.'),
  steps: z.array(z.string().min(1)).min(1).describe('Ordered operation steps as an array of strings.'),
  expectedResult: z.string().min(1).describe('Expected result after executing all steps.'),
  priority: z.enum(['P0', 'P1', 'P2']).describe('Priority: P0 (critical), P1 (high), P2 (medium).')
})

const testCaseGenerateSchema = z.object({
  requirementText: z
    .string()
    .min(TEST_CASE_REQUIREMENT_MIN_LENGTH, `Requirement text must be at least ${TEST_CASE_REQUIREMENT_MIN_LENGTH} characters.`)
    .describe(
      'Full requirement description in Chinese. Must include functional rules, input/output constraints, and business scenarios. Minimum 20 characters.'
    ),
  granularity: z.enum(['basic', 'detailed']).optional().describe('Case granularity: basic (concise) or detailed (step-by-step). Defaults to basic.'),
  testCases: z
    .array(testCaseItemSchema)
    .optional()
    .describe(
      'Structured test cases generated by the model. Must cover normal flow, abnormal flow, and boundary conditions. Auto-assign P0/P1/P2 priority.'
    )
})

const testCaseSaveProjectSchema = z.object({
  requirementText: z.string().min(1).describe('Requirement description used to generate the cases.'),
  granularity: z.enum(['basic', 'detailed']).optional().describe('Granularity used for generation.'),
  testCases: z.array(testCaseItemSchema).min(1).describe('Validated test cases to persist to the library.')
})

const testCaseListSchema = z.object({
  search: z.string().optional().describe('Keyword to search requirement text.'),
  page: z.number().int().min(1).optional().describe('Page number. Defaults to 1.'),
  pageSize: z.number().int().min(1).max(50).optional().describe('Page size. Defaults to 20.')
})

const testCaseDeleteSchema = z.object({
  projectId: z.string().min(1).describe('Test case project id to delete.')
})

@Injectable()
@AgentMiddlewareStrategy(TEST_CASE_GENERATOR_MIDDLEWARE_NAME)
export class TestCaseGeneratorMiddleware implements IAgentMiddlewareStrategy<Record<string, never>> {
  meta: TAgentMiddlewareMeta = {
    name: TEST_CASE_GENERATOR_MIDDLEWARE_NAME,
    label: {
      en_US: 'Test Case Generator',
      zh_Hans: '测试用例智能生成'
    },
    description: {
      en_US: 'Generate structured test cases from requirement descriptions and save them to the test case library.',
      zh_Hans: '根据需求描述智能生成结构化测试用例，并保存到用例库。'
    },
    icon: {
      type: 'svg',
      value: TEST_CASE_GENERATOR_ICON,
      color: '#1D4ED8'
    },
    features: [TEST_CASE_GENERATOR_FEATURE],
    configSchema: {
      type: 'object',
      properties: {},
      required: []
    }
  }

  constructor(private readonly service: TestCaseGeneratorService) {}

  createMiddleware(_options: Record<string, never>, context: IAgentMiddlewareContext): PromiseOrValue<AgentMiddleware> {
    const scope = scopeFromContext(context)

    const generateTool = tool(
      async (input: z.infer<typeof testCaseGenerateSchema>) => {
        const requirementText = input.requirementText?.trim() ?? ''
        if (requirementText.length < TEST_CASE_REQUIREMENT_MIN_LENGTH) {
          return JSON.stringify({
            success: false,
            errorCode: 'INVALID_INPUT',
            message: `需求描述过于简略（当前 ${requirementText.length} 字，至少需要 ${TEST_CASE_REQUIREMENT_MIN_LENGTH} 字），请补充功能规则、输入输出约束等细节后重新生成。`,
            data: null
          })
        }

        const generatedCases = (input.testCases ?? []).filter(validateGeneratedTestCase)
        if (!generatedCases.length) {
          return JSON.stringify({
            success: false,
            errorCode: 'INVALID_INPUT',
            message: '未能生成有效的测试用例，请确保需求描述包含明确的功能规则和业务场景。',
            data: null
          })
        }

        return JSON.stringify({
          success: true,
          message: `已根据需求描述生成 ${generatedCases.length} 条测试用例。`,
          data: {
            requirementText,
            granularity: input.granularity ?? 'basic',
            testCases: generatedCases
          }
        })
      },
      {
        name: TEST_CASE_GENERATE_TOOL_NAME,
        description:
          'Generate structured test cases from a requirement description. The requirement text must be at least 20 characters and include functional rules, input/output constraints, and business scenarios. The generated cases must cover normal flow, abnormal flow, and boundary conditions, with auto-assigned P0/P1/P2 priorities. If the input is too short or semantically vague, return INVALID_INPUT error instead of forcing generation.',
        schema: testCaseGenerateSchema
      }
    )

    const saveProjectTool = tool(
      async (input: z.infer<typeof testCaseSaveProjectSchema>) => {
        const project = await this.service.saveProject(
          {
            requirementText: input.requirementText,
            granularity: input.granularity,
            testCases: input.testCases as TestCaseSaveProjectInput['testCases']
          },
          scope
        )
        return JSON.stringify({
          success: true,
          message: 'Test case project was saved to the library.',
          data: {
            id: project.id,
            requirementText: project.requirementText,
            granularity: project.granularity,
            testCaseCount: project.testCases?.length ?? 0,
            createdAt: project.createdAt
          }
        })
      },
      {
        name: TEST_CASE_SAVE_TOOL_NAME,
        description:
          'Save a generated test case project and its test cases to the persistent library. Call this after test_case_generate produces valid cases the user wants to keep.',
        schema: testCaseSaveProjectSchema
      }
    )

    const listProjectsTool = tool(
      async (input: z.infer<typeof testCaseListSchema>) => {
        const result = await this.service.listProjects(scope, input)
        return JSON.stringify({
          success: true,
          message: 'Test case projects were listed.',
          data: result
        })
      },
      {
        name: TEST_CASE_LIST_TOOL_NAME,
        description:
          'List saved test case projects with pagination and optional keyword search. Use this when the user asks about existing test case history.',
        schema: testCaseListSchema
      }
    )

    const deleteProjectTool = tool(
      async (input: z.infer<typeof testCaseDeleteSchema>) => {
        await this.service.deleteProject(scope, input.projectId)
        return JSON.stringify({
          success: true,
          message: 'Test case project was deleted.',
          data: { id: input.projectId }
        })
      },
      {
        name: TEST_CASE_DELETE_TOOL_NAME,
        description: 'Delete one test case project and all its test cases by project id.',
        schema: testCaseDeleteSchema
      }
    )

    return {
      name: TEST_CASE_GENERATOR_MIDDLEWARE_NAME,
      tools: [generateTool, saveProjectTool, listProjectsTool, deleteProjectTool]
    }
  }
}

function scopeFromContext(context: IAgentMiddlewareContext): TestCaseScope {
  return {
    tenantId: context.tenantId,
    organizationId: context.organizationId,
    userId: context.userId,
    assistantId: context.xpertId,
    conversationId: context.conversationId
  }
}
