packages:
  - ../packages/*
  - apps/*
  - packages/*
  - integrations/*
  - examples/*
  - tools/*
  - models/*
  - databases/*
  - middlewares/*
  - skills/*

overrides:
  '@xpert-ai/plugin-sdk@3.12.1>@xpert-ai/contracts': 3.12.1

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@sap/hana-client'
  - '@swc/core'
  - cpu-features
  - msgpackr-extract
  - nx
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver

allowBuilds:
  '@nestjs/core': true
  '@sap/hana-client': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
