export const GEO_PLUGIN_NAME = '@community/apps-geo-intelligence-workspace'
export const GEO_FEATURE = 'geo_intelligence_workspace'
export const GEO_PROVIDER = 'geo_intelligence'
export const GEO_MIDDLEWARE = 'GeoIntelligenceMiddleware'
export const GEO_VIEW_KEY = 'workbench'
export const GEO_REMOTE_ENTRY = 'geo-intelligence'
export const GEO_MONITOR_TOOL = 'geo_monitor_prompt'
export const GEO_LIST_TOOL = 'geo_list_runs'
export const GEO_ICON = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#dbeafe"/><path d="M12 45L25 31L35 37L52 17" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="52" cy="17" r="5" fill="#1d4ed8"/></svg>'
